<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete modal</name>
   <tag></tag>
   <elementGuidId>4716ab69-eef7-4f21-b4dc-9f6025e43b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Delete Contact Are you sure you want to delete contact? DeleteCancel' or . = 'Delete Contact Are you sure you want to delete contact? DeleteCancel')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>6078ef88-ac3b-4528-921d-222a3b4f3169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fd6d1d63-6974-4af2-a7d2-26b315295e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b05dcda0-e333-4a50-ad11-27392d16ec56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-51 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>352b56ef-5091-4479-b70a-c86acccddebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-1</value>
      <webElementGuid>ecb66aec-9dc3-4f6b-8df0-164268bb9f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>36d8cc57-40b6-4a38-b50b-371d0a8c53ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-1</value>
      <webElementGuid>027f8b2b-431a-45d1-9dfc-7eef24a1a987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Contact Are you sure you want to delete contact? DeleteCancel</value>
      <webElementGuid>b5e21f5b-7417-4a49-b294-467569a19baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)</value>
      <webElementGuid>ba386219-7348-41d3-a93c-cc3fd3c9d8af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']</value>
      <webElementGuid>4c3f5b02-ddf8-4770-9416-522dbf7fa165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-6']/mat-dialog-container</value>
      <webElementGuid>4bc7ed96-af03-48c4-a5d2-9c9945105f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-1', '&quot;', ')')])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>609e1a09-16a5-4867-8583-00c00d5b0eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::mat-dialog-container[1]</value>
      <webElementGuid>6018bdb6-2b1c-4b21-8f6b-fc6398845255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>7b02594b-6e85-404a-8916-c48eecfbad55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-1' and (text() = 'Delete Contact Are you sure you want to delete contact? DeleteCancel' or . = 'Delete Contact Are you sure you want to delete contact? DeleteCancel')]</value>
      <webElementGuid>a218c0c1-31ec-4933-b718-78317904160e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
