<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Invite New User</name>
   <tag></tag>
   <elementGuidId>fd1e4e4a-495e-481b-81bb-0c09ffde9312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4[@class = 'mat-dialog-title' and (text() = 'Invite New User' or . = 'Invite New User')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[text()='Invite New User']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>5b0c2750-b608-45bf-b795-4c165a626345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>aeda3589-ebaa-4bc8-abb5-f4c3fa584aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-5</value>
      <webElementGuid>4a750d3d-86c3-4966-ad80-4c6abc2f25fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invite New User</value>
      <webElementGuid>4b22049d-a8cd-4b17-bade-06b024f8db0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-5&quot;)</value>
      <webElementGuid>dba3ac71-4887-4316-8d7c-c63083f3a349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-5']</value>
      <webElementGuid>33f076ff-f00e-45e9-9911-15df79e03588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-5']/app-dialog-add-user/section/h4</value>
      <webElementGuid>82fd1fb5-b163-4905-9967-6683ff1eba32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work'])[3]/following::h4[1]</value>
      <webElementGuid>31b5120b-4108-41de-9722-e3e831177ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto country'])[1]/following::h4[1]</value>
      <webElementGuid>b4168f08-4edd-4f82-8b9d-6e48b26a9b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::h4[1]</value>
      <webElementGuid>ff25cd8f-9267-4cc3-8b3a-bcdb78cf9312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Settings'])[1]/preceding::h4[1]</value>
      <webElementGuid>d41ca6ae-7a06-419f-a12c-824e03d7eb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invite New User']/parent::*</value>
      <webElementGuid>952645f0-a310-4c64-8ec3-c6cd4e01d500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/h4</value>
      <webElementGuid>a894b67d-9d43-4508-bf2b-0d84752dd87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-5' and (text() = 'Invite New User' or . = 'Invite New User')]</value>
      <webElementGuid>a6a10319-36ad-4011-b351-332f703fee19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
