<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Invite new user modal</name>
   <tag></tag>
   <elementGuidId>83ae0184-a670-4886-9f26-d74b04a5cc88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel' or . = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>ee13c718-c22d-4373-a9e7-cd86bdef3de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3e76cbc8-e32c-4bf4-8162-99b6e753dedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c31d3ac7-56a5-4781-90ba-351513b8cd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-102 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>055297f4-9396-4ad7-857d-de0b45709d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-1</value>
      <webElementGuid>059e5141-5a6b-49e5-840d-c1fb94bb034a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>95cef879-96b6-4c66-b6df-09879db6b616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-1</value>
      <webElementGuid>c15401d7-3353-4665-aac6-8e0e90f6ca22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel</value>
      <webElementGuid>575c7d6b-7506-440b-8e2a-c7797856518e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)</value>
      <webElementGuid>0a32eeab-4396-4c08-9ee5-3c71fb71be50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']</value>
      <webElementGuid>ba817540-6411-4089-9161-8ea196e0932d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-39']/mat-dialog-container</value>
      <webElementGuid>7eb6ec89-4a94-47b4-961d-ffcbfaf36cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work'])[3]/following::mat-dialog-container[1]</value>
      <webElementGuid>a8b0a078-0904-4969-b05a-c1e29fd5f3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto country'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>134e6295-5391-4d3d-89ae-2ec28e9cf131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>fd6076b6-0099-40f7-b4ce-d4a981929cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-1' and (text() = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel' or . = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel')]</value>
      <webElementGuid>2406148c-3a5f-4b27-8f8f-7a808096e165</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
