<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notes</name>
   <tag></tag>
   <elementGuidId>ecd51fca-280f-46ce-90ba-6e791affe9fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@name = 'note' and @placeholder = 'Add a note to this contact...']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@data-placeholder='Add a note to this contact...']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-37</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4d4e8aab-aaf8-4608-af35-460d9972d93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>cda7d99f-a969-4df8-86de-04a5ac2b395c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>7a48c1fd-514e-4950-aace-0edab9063b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>280</value>
      <webElementGuid>e83b6f3e-4b04-43a6-9ebf-5d8b3dd12dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c110-126 cdk-text-field-autofill-monitored ng-valid ng-dirty ng-touched</value>
      <webElementGuid>8c28bb20-7624-4ee3-b658-cd6ea80c7e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>280</value>
      <webElementGuid>f3107feb-4068-41da-9327-6e3f01626556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>158bdcf8-e516-416b-8f48-8d20e80b159d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-placeholder</name>
      <type>Main</type>
      <value>Add a note to this contact...</value>
      <webElementGuid>00029d87-7fdf-457f-92eb-c5f5f88358f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-37</value>
      <webElementGuid>254fd730-d76d-479d-96bf-eb03d7f4c664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add a note to this contact...</value>
      <webElementGuid>d843bcd8-30fb-4079-a33e-2f0d5de66a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d19ea6f6-cf6d-4d5b-aa32-937e5ade54ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4951a35e-485f-46a9-bba8-edc87e041f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-37&quot;)</value>
      <webElementGuid>6b538bb9-194e-436b-a8aa-7ae1d4f31f9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='mat-input-37']</value>
      <webElementGuid>a8b4b7a0-2dc2-490c-999b-747a08899f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-1-0']/div/section/div/div[3]/div/mat-form-field/div/div/div/textarea</value>
      <webElementGuid>87b483ce-1bd7-442c-b6b9-3a057e9bea51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9bdd2de0-b8b2-4a18-8b64-c26e7bd8e770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'note' and @id = 'mat-input-37' and @placeholder = 'Add a note to this contact...']</value>
      <webElementGuid>71e0c28b-46ab-42a1-8047-514bc5be3e13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
