<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Role</name>
   <tag></tag>
   <elementGuidId>f63c0183-8c85-41c7-975e-d4a38fd33481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'RoleRole *' or . = 'RoleRole *')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//mat-icon[@data-mat-icon-name='user'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c110-126</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>949eee35-8d11-4ce0-a09e-42a07931e7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c110-126</value>
      <webElementGuid>ab6dfe5c-af48-4fa7-aca3-7925f40b8faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RoleRole *</value>
      <webElementGuid>01f5250a-df2f-4a1d-bc36-096c00c54fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-4-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-129 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;push-top-lg ng-star-inserted&quot;]/div[1]/div[4]/mat-list[@class=&quot;mat-list mat-list-base&quot;]/mat-list-item[@class=&quot;mat-list-item mat-focus-indicator mat-list-item-avatar mat-list-item-with-avatar&quot;]/div[@class=&quot;mat-list-item-content&quot;]/div[@class=&quot;mat-list-text&quot;]/span[@class=&quot;mat-line&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c110-126 mat-primary mat-form-field-type-mat-select mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c110-126&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c110-126&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c110-126&quot;]</value>
      <webElementGuid>c10dc354-a7a1-4c51-ad73-4b38322ccba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-4-0']/div/div/div/div[4]/mat-list/mat-list-item/div/div[3]/span/mat-form-field/div/div/div</value>
      <webElementGuid>6a197b12-4411-42f0-8b61-8d72da3fca8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::div[12]</value>
      <webElementGuid>4f8f709d-f0e6-43b2-a4a6-806a14017939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::div[24]</value>
      <webElementGuid>f7128e20-2de7-47e1-9502-74e2fc518cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/mat-list/mat-list-item/div/div[3]/span/mat-form-field/div/div/div</value>
      <webElementGuid>990292bc-5e27-4282-8992-7aee9f6fde6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'RoleRole *' or . = 'RoleRole *')]</value>
      <webElementGuid>bf47a16c-fe6d-4504-a06f-e7206712603c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
