<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Active_forms_assisted_report</name>
   <tag></tag>
   <elementGuidId>31ff4d6e-4e81-423b-90c1-d920da846b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-icon[text()='people']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f592d704-7ac6-4143-b76b-600dacbeeeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1692098972184</value>
      <webElementGuid>3d5292a2-2ca6-43d1-a042-17b54f412c20</webElementGuid>
   </webElementProperties>
</WebElementEntity>
