<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Active_forms_update</name>
   <tag></tag>
   <elementGuidId>3d26dbe9-41de-41e2-863b-6af878b5ade9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-icon[text()='collections']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6cda5388-0d6a-4ea1-8d00-f8ab285682e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1692099017449</value>
      <webElementGuid>92dcf924-6f97-44b8-a126-88e72a4f8241</webElementGuid>
   </webElementProperties>
</WebElementEntity>
