<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assisted_report_Submit_button</name>
   <tag></tag>
   <elementGuidId>cf91b314-f561-4db4-983f-471cf23a758e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'mat-focus-indicator text-upper')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d63fac3f-e78c-4874-af6d-ab3d6f2be30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1692279666661</value>
      <webElementGuid>ef06cc5d-0eb7-4b86-bfc6-8dbcf19951f6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
