<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assisted_report_q2_No</name>
   <tag></tag>
   <elementGuidId>4be43810-92dc-4015-b0fe-618a323b05a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'mat-focus-indicator NoButton')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e77e1b06-b977-499b-80f0-53ff37c0ad95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1692279036565</value>
      <webElementGuid>5f35dc4f-bee1-4b58-8711-8c1de837b2df</webElementGuid>
   </webElementProperties>
</WebElementEntity>
