<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Eye_Info_Tracker_Cancel_button</name>
   <tag></tag>
   <elementGuidId>9439d25d-4376-422f-b8f4-d37965281457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'mat-focus-indicator text-upper')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>79bb2979-6268-4d14-924b-af2bd800075b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1691638746139</value>
      <webElementGuid>2767905a-2617-420a-83ed-3bd5936229ac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
