<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Self_report_modal</name>
   <tag></tag>
   <elementGuidId>6facb537-0bf4-437c-a1e6-b6019bc80b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='cdk-visually-hidden cdk-focus-trap-anchor']/following-sibling::mat-dialog-container[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>a2089c6a-912b-4d55-b955-6d964631af0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3696d970-fecd-445c-a596-602dd5fe12ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container cdk-dialog-container ng-tns-c39-39 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>11d396a4-275f-45f2-ad5a-31350f82a487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>ffa62e99-af1e-4ff7-9769-34fd19d7e14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>8f8f884e-412c-4d78-a18a-fc9bfc9b0b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9361c4d-6c14-4b2f-a72f-5a2704232e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self ReportclearReport Date *Add For Have you experienced a fever of 100.4 degrees Fahrenheit or greater, a new cough, new loss of taste or smell, or shortness of breath within the past 10 days?   No  Yes In the past 10 days, have you tested positive for COVID-19 using a test that tested saliva or used a nose or throat swab (not a blood test)? (10 days measured from the date you were tested, not the date you received the test result.)   No  Yes To the best of your knowledge, in the past 14 days, have you been in close contact (within 6 feet for at least 10 minutes) with anyone while they had COVID-19?   No  Yes In the past 14 days, have you traveled internationally or returned from a state identified by New York State as having widespread community transmission of COVID-19 (other than just passing through the restricted state for less than 24 hours)? Visit https://coronavirus.health.ny.gov/covid-19-travel-advisory for applicable states.   No  Yes CANCEL       SUBMIT check_circle_outline          </value>
      <webElementGuid>8e41a0f3-2561-4b81-8dee-3d7bf28632cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>181671d7-623f-40ba-9f05-fe9a3021fafd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>e42ab995-8f39-4e81-9e05-80afa0660a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-8']/mat-dialog-container</value>
      <webElementGuid>cf1ed72b-64d5-4f7d-a028-6d5a1cd2ee08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>0a031092-064a-4a62-a053-1a9c8081cba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report for Others'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>7b003a05-fcdb-46f6-8cdf-8b47be250740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>4420fcb4-a6fa-4cb8-ba4a-75fc424f8f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Self ReportclearReport Date *Add For Have you experienced a fever of 100.4 degrees Fahrenheit or greater, a new cough, new loss of taste or smell, or shortness of breath within the past 10 days?   No  Yes In the past 10 days, have you tested positive for COVID-19 using a test that tested saliva or used a nose or throat swab (not a blood test)? (10 days measured from the date you were tested, not the date you received the test result.)   No  Yes To the best of your knowledge, in the past 14 days, have you been in close contact (within 6 feet for at least 10 minutes) with anyone while they had COVID-19?   No  Yes In the past 14 days, have you traveled internationally or returned from a state identified by New York State as having widespread community transmission of COVID-19 (other than just passing through the restricted state for less than 24 hours)? Visit https://coronavirus.health.ny.gov/covid-19-travel-advisory for applicable states.   No  Yes CANCEL       SUBMIT check_circle_outline          ' or . = 'Self ReportclearReport Date *Add For Have you experienced a fever of 100.4 degrees Fahrenheit or greater, a new cough, new loss of taste or smell, or shortness of breath within the past 10 days?   No  Yes In the past 10 days, have you tested positive for COVID-19 using a test that tested saliva or used a nose or throat swab (not a blood test)? (10 days measured from the date you were tested, not the date you received the test result.)   No  Yes To the best of your knowledge, in the past 14 days, have you been in close contact (within 6 feet for at least 10 minutes) with anyone while they had COVID-19?   No  Yes In the past 14 days, have you traveled internationally or returned from a state identified by New York State as having widespread community transmission of COVID-19 (other than just passing through the restricted state for less than 24 hours)? Visit https://coronavirus.health.ny.gov/covid-19-travel-advisory for applicable states.   No  Yes CANCEL       SUBMIT check_circle_outline          ')]</value>
      <webElementGuid>7b891636-c67b-4075-92d3-b1e16ba01e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
