<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1691047687576</name>
   <tag></tag>
   <elementGuidId>1f78e748-0544-4827-b11b-f33dcc2b2083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ng-star-inserted']//pre[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e01aa484-105b-46e5-a336-14668c6d8a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1691047687576</value>
      <webElementGuid>b3ec5f9a-e77b-478d-bfe4-a4b4c0326a5a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
