<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add</name>
   <tag></tag>
   <elementGuidId>5ad3425b-b231-4e06-872f-829762532533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@permission-type='OU_INVITE_CREATE'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.ng-tns-c653-37.mat-mini-fab.mat-button-base.mat-primary.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @permission-type = 'OU_INVITE_CREATE' and (text() = 'add' or . = 'add')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f849e3f-9f0a-45b3-af13-a210c15ef722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53228362-843d-41ed-9387-53ae78daa33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f4e8569d-4f55-4798-8ab3-4727bfb851e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>permission-type</name>
      <type>Main</type>
      <value>OU_INVITE_CREATE</value>
      <webElementGuid>28dcb291-94aa-4682-ba51-a24ad161ec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator ng-tns-c653-37 mat-mini-fab mat-button-base mat-primary cdk-focused cdk-mouse-focused</value>
      <webElementGuid>10c70606-3cf4-453a-b002-274cd6a1b4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>a69a6733-5b6e-4159-869b-026707997f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-permission-type</name>
      <type>Main</type>
      <value>OU_INVITE_CREATE</value>
      <webElementGuid>d9c56fab-0b66-4c69-9ad1-97fe910cb824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>c9ab1295-b6de-4ebd-b84c-c42655efdecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-48 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;white-container ng-tns-c653-37&quot;]/div[@class=&quot;button-add-user ng-tns-c653-37&quot;]/button[@class=&quot;mat-focus-indicator ng-tns-c653-37 mat-mini-fab mat-button-base mat-primary cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>e5af299a-1f3f-4182-886f-262ec44ccfa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>b7d9a19c-ade8-49ed-8a0c-ed65d194b136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div/div/button</value>
      <webElementGuid>e9f064b7-2542-4acb-9667-afc26aaa4b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request to Join Users'])[1]/following::button[1]</value>
      <webElementGuid>d4c50fe3-b861-4d3a-8a59-198a31c03305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invited Users'])[1]/following::button[1]</value>
      <webElementGuid>91845795-43e0-40e6-bda9-8e25721733ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing users from all organization units'])[1]/preceding::button[1]</value>
      <webElementGuid>48ee4866-5bff-41c8-a07d-42299a82e997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>dff2a990-8954-46fd-8250-aeefa43d9399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'add' or . = 'add')]</value>
      <webElementGuid>81918db9-1550-4981-ae32-e68e99718119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
