<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_email already exists</name>
   <tag></tag>
   <elementGuidId>1fd6950b-6acf-4707-b7cb-8838c01676df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-error[@role = 'alert' and (text() = ' testuser01@mailinator.com already exists. Please enter another ID' or . = ' testuser01@mailinator.com already exists. Please enter another ID')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[text()=' testuser01@yopmail.com already exists. Please enter another ID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-error-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>ce66a590-64ba-43ab-8aa3-09dd0931f427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>01e4f9b9-9c83-470b-920c-e8482d12a164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error ng-tns-c238-76 ng-star-inserted</value>
      <webElementGuid>ce3b6447-9865-4976-9ccb-9c1d303d89db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-5</value>
      <webElementGuid>5af025c9-ceee-41b4-91c5-e8a4e73f78f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> testuser01@mailinator.com already exists. Please enter another ID</value>
      <webElementGuid>0e89459b-ac9c-44cd-a015-750126d9b3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-5&quot;)</value>
      <webElementGuid>f7ef4cf4-90f4-4f49-a7f5-cfb2a4e5f44f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-5']</value>
      <webElementGuid>77c14588-9ce7-4846-8ed9-702ec98dda5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::mat-error[1]</value>
      <webElementGuid>13121205-1600-49a5-a4d9-d169ca632bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>4afff5a5-568d-4ac6-99fe-102458f28c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>8e15bb68-1311-4261-9af0-d84f77136816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='testuser01@mailinator.com already exists. Please enter another ID']/parent::*</value>
      <webElementGuid>9f916f6e-aa67-4407-b984-acbbc6d159a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>10673c62-a2f9-4f41-820d-d71fa12e0da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-5' and (text() = ' testuser01@mailinator.com already exists. Please enter another ID' or . = ' testuser01@mailinator.com already exists. Please enter another ID')]</value>
      <webElementGuid>3b882abc-ff99-4cd8-9fdb-93de72d56257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
