<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_General</name>
   <tag></tag>
   <elementGuidId>b2c1f673-5604-4ee4-b283-211967ff1f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-main-page/div/mat-sidenav-container/mat-sidenav-content/div[1]/div[3]/app-teams/div/mat-drawer-container/mat-drawer/div/div/perfect-scrollbar/div/div[1]/div/div[4]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c628-75.channel.active.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49d756b6-36a7-4497-847f-161268484263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c628-75 channel active ng-star-inserted</value>
      <webElementGuid>bd10a64c-84ed-4980-94d6-c9a6cf66cbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>7d6166e9-c270-44b9-abb5-6492e463335c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>channel-id</name>
      <type>Main</type>
      <value>d8d79dbe-570c-4ba1-88be-570c2c3d9d8b</value>
      <webElementGuid>22e99690-1a7c-4b0f-a47d-77b413c4fa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General</value>
      <webElementGuid>231b8ab4-b5e4-4d31-b7a1-30ca9484e468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c479-5 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c479-5 mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;wrapper&quot;]/app-teams[@class=&quot;ng-tns-c628-75 ng-star-inserted&quot;]/section[@class=&quot;teams-section ng-tns-c628-75&quot;]/div[@class=&quot;teams-channels ng-tns-c628-75&quot;]/perfect-scrollbar[@class=&quot;teams-scrollbar ng-tns-c628-75&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/div[@class=&quot;team ng-tns-c628-75 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c628-75 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c628-75 channel active ng-star-inserted&quot;]</value>
      <webElementGuid>50921d43-bacd-489c-b7ab-18278d8d6527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Team Private'])[1]/following::div[5]</value>
      <webElementGuid>9881c1ca-0ab2-499b-8c2f-4756f6e6e204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AT'])[1]/following::div[6]</value>
      <webElementGuid>f7627c2e-8cae-4fb3-97ad-a13b059eba5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AT'])[2]/preceding::div[1]</value>
      <webElementGuid>fe3251d1-f12c-4096-bb56-0d27b724e1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>0f769e13-6700-40cc-bfa4-c225bbb229b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'General' or . = 'General')]</value>
      <webElementGuid>ed86e363-964c-4537-8503-fa6c03fd8eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
