<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Successfully edited post msg</name>
   <tag></tag>
   <elementGuidId>0322b42d-db4f-4b34-bba9-0c246ff971d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>snack-bar-container.mat-snack-bar-container.ng-tns-c41-72.ng-trigger.ng-trigger-state.mat-snack-bar-center.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-12']/snack-bar-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>snack-bar-container</value>
      <webElementGuid>67dd773e-3f75-4d01-b100-19460290ce57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-snack-bar-container ng-tns-c41-72 ng-trigger ng-trigger-state mat-snack-bar-center ng-star-inserted</value>
      <webElementGuid>05c2abfd-b96e-496d-bafc-0a522b5b254f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>eeee5b39-1cfd-4ccb-a3b2-e250774484dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successfully edited postOK</value>
      <webElementGuid>6b974f9c-31f9-4bad-869c-12385f9d09d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-12&quot;)/snack-bar-container[@class=&quot;mat-snack-bar-container ng-tns-c41-72 ng-trigger ng-trigger-state mat-snack-bar-center ng-star-inserted&quot;]</value>
      <webElementGuid>fdd35277-ccf7-442f-a096-e4fe7aaeba92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-12']/snack-bar-container</value>
      <webElementGuid>d956d42f-76dd-4ad5-b8f5-3d69482f8a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Successfully edited post'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>285717e0-25db-4730-93ee-8eb2b4e9508e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>4904943a-1522-47ac-a3a6-a9304d9e3bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//snack-bar-container</value>
      <webElementGuid>502a412d-d332-4a19-9885-cf70b2804f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//snack-bar-container[(text() = 'Successfully edited postOK' or . = 'Successfully edited postOK')]</value>
      <webElementGuid>a1eae8e4-6627-44ee-a942-aca70a8e0669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
