<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Successfully deleted post msg</name>
   <tag></tag>
   <elementGuidId>6cb0e882-a0aa-4911-982e-e8ab32706ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>snack-bar-container.mat-snack-bar-container.ng-tns-c41-74.ng-trigger.ng-trigger-state.mat-snack-bar-center.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-15']/snack-bar-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>snack-bar-container</value>
      <webElementGuid>e765163f-f253-4277-a6c1-18740643e041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-snack-bar-container ng-tns-c41-74 ng-trigger ng-trigger-state mat-snack-bar-center ng-star-inserted</value>
      <webElementGuid>c43b2061-477a-4bbd-801c-07eb7e463d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>49b5fe6a-851d-4498-8048-6cd973ad8580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successfully deleted postOK</value>
      <webElementGuid>afa50bff-baaf-4a4e-80ea-c2e8d3e4d4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-15&quot;)/snack-bar-container[@class=&quot;mat-snack-bar-container ng-tns-c41-74 ng-trigger ng-trigger-state mat-snack-bar-center ng-star-inserted&quot;]</value>
      <webElementGuid>61fec50c-164b-47ee-9b64-f9fdedceaece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-15']/snack-bar-container</value>
      <webElementGuid>91be737d-3e28-45f6-a56e-b1f55030659a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Successfully deleted post'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>c29e28f3-d8d1-46e6-a8d1-99dc3b1b6a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>3a62143c-b40e-4df9-98ce-065ef56f186f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//snack-bar-container</value>
      <webElementGuid>1a8e1ec1-0d1b-4108-8baa-f560dc67e08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//snack-bar-container[(text() = 'Successfully deleted postOK' or . = 'Successfully deleted postOK')]</value>
      <webElementGuid>de5abebf-3041-40ba-b7a3-12150f4af3c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
