<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_Delete Team</name>
   <tag></tag>
   <elementGuidId>dad59882-2472-4084-8b08-a26c66cd1556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel' or . = 'Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>9a5705f9-c5c0-4fe3-90bc-38e722ff8a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>353cfb47-df87-440c-8e6d-b850c3808cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container cdk-dialog-container ng-tns-c39-76 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>3fd24cb6-673b-4c3a-acb1-aeebb800f450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>7995b562-fde9-41c8-8dce-83249adc0463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>411988bc-7076-4cc3-bb0b-7ccde1f6bf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>43ea40d1-ca40-4814-b7ff-f533286ea6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-2</value>
      <webElementGuid>46992751-7ab9-4ecb-a52e-32f0c98841e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel</value>
      <webElementGuid>8af0d49a-a3ba-424d-a31b-267e6c2d2ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>ede4dbee-d11d-471b-a728-be8759a2161e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>52d20630-5f8c-4895-ba01-a51481c9aac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-10']/mat-dialog-container</value>
      <webElementGuid>41bb6e26-8133-4543-bdbc-29085d552717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Team'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>504bec2e-dae3-4cd8-a1b5-c6e6b1bac283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Team'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>07ed228f-91ab-413c-ad7a-0f269348b817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>19bf385a-f21b-4948-b1e1-edab0a976338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel' or . = 'Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel')]</value>
      <webElementGuid>bacfbb1e-0658-4677-8587-3bcbd490faa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
