<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal_Delete Team</name>
   <tag></tag>
   <elementGuidId>dad59882-2472-4084-8b08-a26c66cd1556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel' or . = 'Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>ce296cd9-fd8c-49af-b412-8e16a3984748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c1963160-93fc-4329-bfc7-2f0413818ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container cdk-dialog-container ng-tns-c39-76 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>bdcc4017-694c-425c-8001-65e39f5098f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>5364ceaf-9a6a-4399-aa11-d716709e6948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>ac7187dd-4e6c-4ee6-859e-188b88684fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7957005f-8800-4fc2-8459-1b820a73f987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-2</value>
      <webElementGuid>458f5832-3861-446f-a7a0-761ffa775343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel</value>
      <webElementGuid>f4d93e5e-c59f-4c0d-bc86-98abea7d94da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>e708970b-b39d-4a6c-84d1-6e0841dbef22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>ca924673-950d-4cbd-a04a-c809eb51058e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-10']/mat-dialog-container</value>
      <webElementGuid>d89c677b-a2ac-4350-92db-16c7a5551cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Team'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>11ee373d-4ad8-4e84-ba32-130f4c865c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Team'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>4a8dcae1-d643-4407-94a0-4690d14f825a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>74881dc0-6c64-46b6-b623-b6f9c4ad1352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel' or . = 'Delete Team Are you sure you want to delete team Auto Team Public edit? Warning! All resources associated with this team will be permanently deleted.DeleteCancel')]</value>
      <webElementGuid>7906d459-8e57-4c7d-80eb-1a5dc4dfa9ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
