<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Activation link</name>
   <tag></tag>
   <elementGuidId>09bcdc74-0914-45d1-8090-6a9440772598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/p[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://url3277.everleagues.com/ls/click?upn=qGh8JnXjGPKyGOnBmhsRbPCo0lcmyZHTi4Mb-2FaqCSUgK8pL-2FZTM7tIiTXcG0eAj-2F-2FB8OYKKBj5u59tGjVnh-2BOrQEAWBL6g1NSazcKQEFhZ-2BI-2BczGN2DJjoyGdh4KLcmeZec5MRFI23t-2FK7I7M8Lo9evEIewegW2ut7gyx1mhWar-2BF1BAUQ9IcioRV27l5VLAg2-2BxG9mliypijM5b2YDFExl5w-2FgF13-2BeC-2BfyeI5ZkMz-2FA32-2BQiqPuAvXmGtyiI-2BMOZqM1VnHJfLS5xmyWNz-2FRoOa75PMbtFl0xy3q6rEKXGXevJTolVYxTPfZLZZ6HSSXCOBRitLygHSRVAF1HZNGVtKK6X9PBivYdLP7MnBhvk-3DnFCX_XP-2BornThtp-2FC-2Bw-2FBKsD8d4CfjJABm5SjOifXF-2FHG0KpYa7JNRQh-2BiPzGxxgFf6I6b-2FwlUosDxlWVJK17e3Mfr5mSU1xjI7QGpH7PaaBs55wKAZG9NGp1OSmM3PW4VSdOMxPY6XUIT3gdevJ5sD8g3GriM6bxecbDTn1gfusvbSBBAPv3CIOnurlPNlKuWy6Q0-2BsnObbOLugJcLBdQHGCYrXZWte3M2uCATZAYu8DJfo-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_other</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activation link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/p[3]/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/00-Signup and Activation/Mailinator/iframe_EMAIL BODY</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Activation link')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Activation link']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://url3277.everleagues.com/ls/click?upn=qGh8JnXjGPKyGOnBmhsRbPCo0lcmyZHTi4Mb-2FaqCSUgK8pL-2FZTM7tIiTXcG0eAj-2F-2FB8OYKKBj5u59tGjVnh-2BOrQEAWBL6g1NSazcKQEFhZ-2BI-2BczGN2DJjoyGdh4KLcmeZec5MRFI23t-2FK7I7M8Lo9evEIewegW2ut7gyx1mhWar-2BF1BAUQ9IcioRV27l5VLAg2-2BxG9mliypijM5b2YDFExl5w-2FgF13-2BeC-2BfyeI5ZkMz-2FA32-2BQiqPuAvXmGtyiI-2BMOZqM1VnHJfLS5xmyWNz-2FRoOa75PMbtFl0xy3q6rEKXGXevJTolVYxTPfZLZZ6HSSXCOBRitLygHSRVAF1HZNGVtKK6X9PBivYdLP7MnBhvk-3DnFCX_XP-2BornThtp-2FC-2Bw-2FBKsD8d4CfjJABm5SjOifXF-2FHG0KpYa7JNRQh-2BiPzGxxgFf6I6b-2FwlUosDxlWVJK17e3Mfr5mSU1xjI7QGpH7PaaBs55wKAZG9NGp1OSmM3PW4VSdOMxPY6XUIT3gdevJ5sD8g3GriM6bxecbDTn1gfusvbSBBAPv3CIOnurlPNlKuWy6Q0-2BsnObbOLugJcLBdQHGCYrXZWte3M2uCATZAYu8DJfo-3D']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
   </webElementXpaths>
</WebElementEntity>
