<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Activation link</name>
   <tag></tag>
   <elementGuidId>c7945033-e9e2-4b85-a86b-70dc687b6b01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Activation link')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>15e1808a-0c35-4d4b-84db-c16ba261e4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://xukp7.app.goo.gl/?link=https://everleagues.com/MDljMDExYzMtN2FmYS00N2U2LWIwMzUtMzk5Y2IyNjgwZjIw@a&amp;apn=com.everleague.app&amp;isi=1316297335&amp;ibi=com.everleague.app&amp;dfl=https://lab.everleagues.com/activate/MDljMDExYzMtN2FmYS00N2U2LWIwMzUtMzk5Y2IyNjgwZjIw&amp;efr=1</value>
      <webElementGuid>0a57e07c-fbb0-48cd-9c1f-f03b6047de9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_other</value>
      <webElementGuid>3a9c6cf5-c0d8-4157-b191-e7c3d4021b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>acf0c49a-16fc-4ed2-809e-8b1f3d547bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activation link</value>
      <webElementGuid>13ce2efe-4cb5-4ae4-9941-99c502e63a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/p[3]/a[1]</value>
      <webElementGuid>e00d808b-82d2-42ea-ae10-87454879af7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mailinator/iframe_-- HTML EMAIL BODY --</value>
      <webElementGuid>db2efb9a-7c0d-4634-ae66-88ac888f0219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Activation link')]</value>
      <webElementGuid>0f472ecb-1475-4dda-8706-d1b9430d54af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Activation link']/parent::*</value>
      <webElementGuid>2b1a944d-c7dd-4d8c-9298-f45cf86f68ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://xukp7.app.goo.gl/?link=https://everleagues.com/MDljMDExYzMtN2FmYS00N2U2LWIwMzUtMzk5Y2IyNjgwZjIw@a&amp;apn=com.everleague.app&amp;isi=1316297335&amp;ibi=com.everleague.app&amp;dfl=https://lab.everleagues.com/activate/MDljMDExYzMtN2FmYS00N2U2LWIwMzUtMzk5Y2IyNjgwZjIw&amp;efr=1')]</value>
      <webElementGuid>9266a6ec-85fa-4755-a7a9-d5953ee2aee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7bac8b7c-7108-425c-8914-7ce225321485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
