<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOGIN_search</name>
   <tag></tag>
   <elementGuidId>ffd7eece-40e6-4708-ad40-cb5b0a2cc08c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;search&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-mobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9301f856-a4d0-47f9-88ec-61982a1b17c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36b81311-26b1-4d90-be9f-d78fc691e7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>110de6e3-5e97-4f63-b71f-6cec03ae57ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-mobile</value>
      <webElementGuid>923cd1a4-6087-41dd-9748-195f666d9c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Public Mailinator Inbox</value>
      <webElementGuid>d0965157-78b5-496c-8eef-6f1d52c3762b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter public inbox</value>
      <webElementGuid>9f7aef41-9d65-48db-8880-e2fcc87bee72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-mobile&quot;)</value>
      <webElementGuid>e4e43122-d0c4-4662-9fd1-38722719d032</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-mobile']</value>
      <webElementGuid>e6c38f5b-b746-43b4-a3cd-390bad265638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='site-mobile-header']/div/div/div/div/div/input</value>
      <webElementGuid>fa2602f7-593b-4c3f-904f-932abc1d1a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header[2]/div/div/div/div/div/input</value>
      <webElementGuid>70057887-feac-41b2-a812-70d51def274a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
