<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Delete Organization Unit modal</name>
   <tag></tag>
   <elementGuidId>da4159e3-acdd-46e6-9581-8835bcd545e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>63f54fc2-5a16-4e7d-978d-8f963af94199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5640fbf2-95c6-4007-8d6c-1ccd79c91a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d7e91cc-7469-4876-b1e2-177b9bc1bad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-131 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>9e9bfd7b-a6e8-45f7-9e47-0dde3c7b547c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-16</value>
      <webElementGuid>d7c946a6-c497-4f95-8184-db0c1b6a9288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>3cbd9a9e-3ce3-43c9-bb1b-90d5a82bad49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-16</value>
      <webElementGuid>6cbc4e41-b48d-4d47-aaaa-235e9d3948bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Organization Unit Are you sure you want to delete Automation Organization Unit? Warning! All resources associated with this root organization will be permanently deleted.DeleteCancel</value>
      <webElementGuid>85495b3a-5758-4fe2-a32d-41e81177723c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-16&quot;)</value>
      <webElementGuid>ebbe6860-8c23-4c49-8c38-7da69d2057f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-16']</value>
      <webElementGuid>f58cbabd-53f9-4f92-91c8-fa0ba4b7fc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-31']/mat-dialog-container</value>
      <webElementGuid>1c9633a3-100e-4a4c-a61f-d91920205254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Organization Unit'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>b7aca4e8-acd6-43ed-82ab-79ac2456cb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Request Link'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>e1342c6d-e818-4ee6-90a0-bdb5fc8febbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>bf2f814d-2ab7-4b14-814b-6de6ec37a64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-16' and (text() = 'Delete Organization Unit Are you sure you want to delete Automation Organization Unit? Warning! All resources associated with this root organization will be permanently deleted.DeleteCancel' or . = 'Delete Organization Unit Are you sure you want to delete Automation Organization Unit? Warning! All resources associated with this root organization will be permanently deleted.DeleteCancel')]</value>
      <webElementGuid>f356ba16-457b-45c2-a182-eaa570ac864b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
