<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Delete Organization Unit</name>
   <tag></tag>
   <elementGuidId>9a5553ae-bc8e-49a4-949d-896adf2be57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>37944db0-3bb5-4625-aa8b-f5a6217f04d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e89d351e-1d28-46bd-9fa9-5901c01c7c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container cdk-dialog-container ng-tns-c39-47 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>199451f9-c1bd-4d7f-ad06-0e157682858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-1</value>
      <webElementGuid>5f8f5622-4a19-4461-b68c-0077e42efd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>f16523dd-c5c7-4370-ab1c-11ee5f3e3289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c41bf926-7f6f-4bc8-93ad-e770643f17e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Organization Unit
            
         Are you sure you want to delete Automation Organization unit? Warning! All resources associated with this root organization will be permanently deleted.CancelDelete</value>
      <webElementGuid>a2231ece-06f7-488a-8a31-ba5cfed9caff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)</value>
      <webElementGuid>03727523-bf0e-487b-b8ba-99ecd7ce844e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']</value>
      <webElementGuid>7bca6377-2ec9-403f-866e-223675cb0592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-4']/mat-dialog-container</value>
      <webElementGuid>c9bd6c4b-26a6-4c60-83e1-e34213f68c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>189f229e-c790-407f-9cd2-f279ae22d2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-1' and (text() = 'Delete Organization Unit
            
         Are you sure you want to delete Automation Organization unit? Warning! All resources associated with this root organization will be permanently deleted.CancelDelete' or . = 'Delete Organization Unit
            
         Are you sure you want to delete Automation Organization unit? Warning! All resources associated with this root organization will be permanently deleted.CancelDelete')]</value>
      <webElementGuid>6e4e3551-1826-4f88-8c69-9e2b3a685bf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
