<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_Field is required</name>
   <tag></tag>
   <elementGuidId>f6eafc78-4519-4186-b2a7-3b6fa9156257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-error-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-error-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-error[@role = 'alert' and (text() = 'Field is required ' or . = 'Field is required ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>61906403-62ca-4bb8-b721-df8c14434be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>bec5c7c6-3439-4d7c-81b7-96999b5bca35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error ng-tns-c110-37</value>
      <webElementGuid>980276e8-18fa-4246-aba9-b0227b1248eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-1</value>
      <webElementGuid>bd5c8c5a-d990-4335-994e-bd87cb2eb967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Field is required </value>
      <webElementGuid>3a7b543a-94d2-468b-b14e-4c97c27c4fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-1&quot;)</value>
      <webElementGuid>4b453914-35e5-4327-bd65-0582866ad705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-1']</value>
      <webElementGuid>0d0b64c8-a5a4-44fe-9a6c-678baf31183e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-dialog-add-ou/section/form/div/div/mat-form-field[2]/div/div[3]/div/mat-error</value>
      <webElementGuid>27313d8d-8288-4b44-842a-75ae145df3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Unit Name'])[1]/following::mat-error[1]</value>
      <webElementGuid>d04cfa91-cd65-411e-adee-b4ca1f75542a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent Organization Unit Name'])[1]/following::mat-error[1]</value>
      <webElementGuid>c83272ea-bf58-4b7e-9b11-acd3324394c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>b388b44f-3c4a-4887-b403-983bfb9604a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>45683749-f5dd-411a-8c3d-f169d81ea557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Field is required']/parent::*</value>
      <webElementGuid>c5fc84f6-8bb3-488c-a532-8e2b05a86a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>0e937e0a-3e16-4947-999a-7db1e614701f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-1' and (text() = 'Field is required ' or . = 'Field is required ')]</value>
      <webElementGuid>21a04655-24f4-4f0e-9ab8-29f11b9d20d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
