<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_recent-list</name>
   <tag></tag>
   <elementGuidId>99783efb-d38e-4c0f-b9cd-56408e2d4452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.activity-container.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/activity-list/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ceb4df92-9a9f-4c28-ac9a-f1752817fdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>ca104105-a44d-4f9a-8a48-c043d76bd647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activity-container ng-star-inserted</value>
      <webElementGuid>e4cdd87d-ff9f-47f4-8697-a7c98a43db0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-layout</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>94a4b940-fda2-495b-974b-94c49a0ef0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mark all as readGTConnection UpdatedGG tester added Automation Tester as a new contact.11:40 AMGTConnection UpdatedGG tester added Automation Tester as a new contact.2/21GTSuccessfully exported chat messageschat exportMy Drive2/19GTConnection UpdatedGG tester added Automation Tester as a new contact.2/19GTConnection UpdatedGG tester added Automation Tester as a new contact.2/16</value>
      <webElementGuid>0b0eedf1-d8ef-46fe-9f72-4fd336b9cd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c371-51 ng-trigger ng-trigger-translateTab&quot;]/activity-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;activity-container ng-star-inserted&quot;]</value>
      <webElementGuid>a00525e4-d60d-48c4-ba30-191674689382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/activity-list/div/div</value>
      <webElementGuid>a4738542-959a-47ba-9bfa-df0d7b9cdfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archive'])[1]/following::div[5]</value>
      <webElementGuid>490cc792-6e5c-40bb-9e8d-c19d1f74f20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent'])[1]/following::div[7]</value>
      <webElementGuid>903a1404-8c3c-4775-9a61-d7d4c60a2b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//activity-list/div/div</value>
      <webElementGuid>b1e42028-c30b-40af-8e9e-513d16126c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mark all as readGTConnection UpdatedGG tester added Automation Tester as a new contact.11:40 AMGTConnection UpdatedGG tester added Automation Tester as a new contact.2/21GTSuccessfully exported chat messageschat exportMy Drive2/19GTConnection UpdatedGG tester added Automation Tester as a new contact.2/19GTConnection UpdatedGG tester added Automation Tester as a new contact.2/16' or . = 'Mark all as readGTConnection UpdatedGG tester added Automation Tester as a new contact.11:40 AMGTConnection UpdatedGG tester added Automation Tester as a new contact.2/21GTSuccessfully exported chat messageschat exportMy Drive2/19GTConnection UpdatedGG tester added Automation Tester as a new contact.2/19GTConnection UpdatedGG tester added Automation Tester as a new contact.2/16')]</value>
      <webElementGuid>90e01068-0998-4839-80b3-710ab6828caf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
