<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-calendar</name>
   <tag></tag>
   <elementGuidId>e50f8678-4987-4e3e-8165-e9d0c20c47b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-datepicker-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-calendar[@id='mat-datepicker-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-calendar</value>
      <webElementGuid>a47761f5-09ed-4c7d-98ae-c1c5f4036519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-calendar ng-tns-c238-54 ng-trigger ng-trigger-fadeInCalendar</value>
      <webElementGuid>e46887f4-720b-43f9-b219-26ded1cbd64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-datepicker-0</value>
      <webElementGuid>ec161f3a-9a0d-4e82-8e53-223ead97a36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-start-at</name>
      <type>Main</type>
      <value>Thu Feb 23 2023 12:17:09 GMT+0</value>
      <webElementGuid>e04fbac4-a199-4f14-b699-6b82c281cfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-start-view</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>8d3c61ed-77b2-4659-bb5f-8a16c2fc88c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-min-date</name>
      <type>Main</type>
      <value>Thu Feb 23 2023 12:17:09 GMT+0</value>
      <webElementGuid>ef2e3d69-b3ee-4d7f-aa80-a4aa03c1fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-max-date</name>
      <type>Main</type>
      <value>Fri Feb 23 2024 12:17:09 GMT+0</value>
      <webElementGuid>ca7608ae-3031-4e97-877a-eb53baf463c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-selected</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>db53d942-6695-4fa1-b9f3-bc9c24ffaa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FEB 2023SundaySMondayMTuesdayTWednesdayWThursdayTFridayFSaturdayS FEB  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28 </value>
      <webElementGuid>df5b2a56-6fd4-47e8-9bca-1a00050b5b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-datepicker-0&quot;)</value>
      <webElementGuid>61d4df2c-ba69-480c-b6eb-cc93b1fab2c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-calendar[@id='mat-datepicker-0']</value>
      <webElementGuid>5c76b32a-e9fc-41e2-9ed6-86f1fd8594f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/mat-datepicker-content/div[2]/mat-calendar</value>
      <webElementGuid>0471da55-3424-4644-a932-b02e5b6652f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Assignment'])[2]/following::mat-calendar[1]</value>
      <webElementGuid>d3d9fd79-62cd-44da-8ff1-6d83657e3bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite New User'])[1]/following::mat-calendar[1]</value>
      <webElementGuid>3956023b-ae15-42f4-86f2-d89ca8b95699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-calendar</value>
      <webElementGuid>a65eae2f-f65b-47e6-9940-384cb95b5f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-calendar[@id = 'mat-datepicker-0' and (text() = 'FEB 2023SundaySMondayMTuesdayTWednesdayWThursdayTFridayFSaturdayS FEB  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28 ' or . = 'FEB 2023SundaySMondayMTuesdayTWednesdayWThursdayTFridayFSaturdayS FEB  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28 ')]</value>
      <webElementGuid>c700f3ec-3538-4c36-8acb-cac82d52924b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
