<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Manually add a subscription on GG Automation organization before running this test suite.</description>
   <name>09.1 - Settings (Users - Invite users)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>234f32f7-dbd8-464c-8bde-05d7d5df45b9</testSuiteGuid>
   <testCaseLink>
      <guid>2a812aea-d3b9-4340-a023-147b165a4fd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/09 - Settings/01 - Users(Invite new user but field are blank)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8a31ff80-b173-4c7b-8540-a1a7422a4d17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/09 - Settings/26 - User(Invite registered account)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>384b3d87-57c1-40e4-bf1e-ac8ea332521f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98584c1d-a872-492e-9148-9c392daebfaf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4004515d-426b-40c0-9218-adfdd8cfcfc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/09 - Settings/02 - Users(Invite new user as co worker)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6adc8ef0-d342-4aec-b71d-54b821b78d89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eac0490b-932f-44a7-9ad4-effe7075db4f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc846fb0-367f-4ca9-8d0b-e04cb9ce97ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/09 - Settings/03 - Users(Invite new user as client)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f79f34a-b0a3-434a-962f-47010493c3d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad269544-19f3-4f0b-ba6f-c0ad7d9f63e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1e4fc68-4b93-4e61-a18c-bad175fc8b87</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f72a27d-cb5d-491e-97cf-39376997a653</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/09 - Settings/04 - Users(Invite new user as partner)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7574380c-7d0f-441e-9d8f-f2d92e770fc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8cffd12-e8c1-45d6-93c6-62621974ff77</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>136c0cf1-ad3d-498e-9208-0189dbb76e43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/09 - Settings/05 - Users(Invite batch of users via CSV file)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
