<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>14 - Income and Expense</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>47812ad4-8e5f-451c-a7d0-f9062b214684</testSuiteGuid>
   <testCaseLink>
      <guid>36e57c50-fee3-40e2-9597-e21776ffdaa1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/01 - Add Company(required field is blank)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3cd16da1-ca0e-4e16-ae1f-9268dabb1556</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/02 - Add Company(fill out required field)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2156df7-341f-4293-a5fe-cdfeb58fd943</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d4267ef-34cb-421c-913a-2ac590897161</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/03 - Add receipt(required field is blank)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>71a577f6-6875-4f54-a259-7375b50740b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/04 - Add Receipt(Amount is less than 0)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef0e9b9e-a99f-43c7-8763-63e83f2b0708</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61c4b5d0-8b9c-4705-b65c-e27da161a494</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/05 - Add receipt(fill out required field)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2018c832-2793-4429-a688-cde40e1b3701</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4cd273a-ff6e-4f3a-9534-9ee6e01287a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9ee9072-1430-4876-bd85-b9d8025a2918</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67bb8924-cc16-4792-ad6d-4961d11f90eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/06 - Update report - Select Fiscal Year</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6143a087-25fa-45be-86fc-f5fadecaf4e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/07 - Update report - Download As</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6dc511cf-e807-4084-bccb-e539865f6fde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/08 - Update report - View and download receipt</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7999c402-0da2-41a8-942a-4b7807069629</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/09 - Update report - Edit receipt</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>652ca82f-676b-4f33-b68c-261f47654ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>450b9a14-23b5-4edf-b942-79ea6918ba4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb7b122a-6145-40f2-99aa-45f4c05f0473</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84977427-61a1-4787-8142-42c45b03a152</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/10 - Update report - Delete receipt</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b59b9d11-68ff-4386-a964-e27f34db0868</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/11 - Settings</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5384ae-f0c6-4df5-b129-7555ae7ed195</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>345216af-1a4f-4def-beaf-0bcb5c66d63d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/14 - Income and Expense/12 - Delete company</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
