<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_open_in_new</name>
   <tag></tag>
   <elementGuidId>07865e30-9ad9-40f1-8372-941d4c3c0dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-main-page/div/mat-sidenav-container/mat-sidenav-content/div[1]/div[3]/app-dashboard-page/section/div/active-dashboard/div/dashboard-section[2]/mat-card/mat-card-header/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.trailing-btn.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>13dd5a6a-9d00-4fb3-8200-c6dcd5ee8a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7a1b878-1f8b-4b63-9272-95c7ddfaa3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate trailing-btn material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>0a6e243d-2ffc-47a2-9d24-b1cd114d68ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c4f0e46-7e30-4abe-903e-ac0aa4729580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>eb1ae976-9ab6-4bf6-aa55-ab704d39d383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>open_in_new</value>
      <webElementGuid>e1cfd708-3201-457a-969b-4da87fa147dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;light theme-default os-window fuse-splash-screen-hidden&quot;]/app-root[1]/app-main-page[@class=&quot;ng-tns-c505-6 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/div[@class=&quot;absolute inset-0 flex flex-col min-w-0 overflow-hidden ng-tns-c505-6&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container flex-auto h-full ng-tns-c505-6 mat-drawer-transition mat-drawer-container-has-open&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content flex flex-col overflow-hidden&quot;]/div[@class=&quot;flex flex-col flex-auto w-full min-w-0&quot;]/div[@class=&quot;flex flex-col flex-auto ng-tns-c505-6&quot;]/app-dashboard-page[@class=&quot;ng-tns-c636-54 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/section[@class=&quot;ng-tns-c636-54&quot;]/div[@class=&quot;ng-tns-c636-54 ng-star-inserted&quot;]/active-dashboard[@class=&quot;ng-tns-c636-54&quot;]/div[1]/dashboard-section[@class=&quot;vertical-section&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator section&quot;]/mat-card-header[@class=&quot;mat-card-header mat-header section-header&quot;]/div[@class=&quot;mark-unread-div&quot;]/div[2]/mat-icon[@class=&quot;mat-icon notranslate trailing-btn material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>80451041-af57-44d4-9b6b-aa5816148f2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-icon</value>
      <webElementGuid>b0bff3d9-d781-4713-bb65-aaea1f047d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'open_in_new' or . = 'open_in_new')]</value>
      <webElementGuid>936edde3-d7d7-46dc-9b56-f3f208060b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
