<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2FA Phone Number modal</name>
   <tag></tag>
   <elementGuidId>fb992cfa-f84f-4002-bb0e-3e715480fb70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[(text() = 'Edit 2FA Phone Number+1Phone Number *Enter a valid phone numberNextCancel' or . = 'Edit 2FA Phone Number+1Phone Number *Enter a valid phone numberNextCancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Edit 2FA Phone Number+1Phone Number *Enter a valid phone numberNextCancel' or . = 'Edit 2FA Phone Number+1Phone Number *Enter a valid phone numberNextCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>c9a46036-0381-4cc0-83d3-00ac6fe9f4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e3b7af26-e663-4acc-b58d-2bd77678b661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ab0ee1dc-84ed-43c3-ae98-d8ba71343040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-59 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>262aad96-68cd-4e17-95fa-663e7887f6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-1</value>
      <webElementGuid>c8358101-8487-4c43-a1a0-1b944950862f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>46548eb2-9d19-460b-9198-107260078a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-1</value>
      <webElementGuid>23ba75f8-4f7b-4679-abf6-53706056b5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit 2FA Phone Number+1Phone Number *Enter a valid phone numberNextCancel</value>
      <webElementGuid>d5a8317b-3e92-4fbe-98db-3c14f96f02aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)</value>
      <webElementGuid>e101c70a-e38d-4299-b194-6d5401b2f8af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']</value>
      <webElementGuid>706ca841-2a1c-44c2-ad9e-3eeb3788383a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/mat-dialog-container</value>
      <webElementGuid>5fbae3b9-d8c7-4192-9c2c-23395ebc23ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Phone'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>f4120bd0-3c57-4677-a0c5-055cbcfcee7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Email'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>b516e9b8-3106-49cb-8f56-389a6e994e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>56db1f3d-d489-4025-a332-052796687b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-1' and (text() = 'Edit 2FA Phone Number+1Phone Number *Enter a valid phone numberNextCancel' or . = 'Edit 2FA Phone Number+1Phone Number *Enter a valid phone numberNextCancel')]</value>
      <webElementGuid>111e3ff8-2c32-4e5f-a52f-5a3256395353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
