<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Success disable</name>
   <tag></tag>
   <elementGuidId>8d082f9e-5110-4787-882e-c94f67e3033a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-16']/snack-bar-container</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>snack-bar-container.mat-snack-bar-container.ng-tns-c41-95.ng-trigger.ng-trigger-state.mat-snack-bar-center.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//snack-bar-container[@role = 'status' and (text() = 'Successfully disabled Two Factor AuthenticationOK' or . = 'Successfully disabled Two Factor AuthenticationOK')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>snack-bar-container</value>
      <webElementGuid>a26e0ebc-d37a-479f-8d16-1e5c3ca86d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-snack-bar-container ng-tns-c41-95 ng-trigger ng-trigger-state mat-snack-bar-center ng-star-inserted</value>
      <webElementGuid>e0dac3dc-f582-415b-b81a-20024c2b6760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>2b92c6cb-f6b8-4eea-a199-dcbeae58fbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successfully disabled Two Factor AuthenticationOK</value>
      <webElementGuid>61cb03db-b4d6-4fce-9140-12f907d669d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-16&quot;)/snack-bar-container[@class=&quot;mat-snack-bar-container ng-tns-c41-95 ng-trigger ng-trigger-state mat-snack-bar-center ng-star-inserted&quot;]</value>
      <webElementGuid>89586f8d-d827-4496-b573-ea51dd24d3c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-16']/snack-bar-container</value>
      <webElementGuid>a9d278e1-abae-418a-9ee1-c1a9213498f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Successfully disabled Two Factor Authentication'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>172277bd-5490-43cb-8a5f-9358a12e200a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::snack-bar-container[1]</value>
      <webElementGuid>d4b04bed-acdf-4ba3-a865-b4bc2cbec6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//snack-bar-container</value>
      <webElementGuid>109e0a33-9937-436a-af79-6d9530a88ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//snack-bar-container[(text() = 'Successfully disabled Two Factor AuthenticationOK' or . = 'Successfully disabled Two Factor AuthenticationOK')]</value>
      <webElementGuid>e9b54e7f-ae3a-4675-ac7b-068d1c4b0848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
