<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add new contact modal</name>
   <tag></tag>
   <elementGuidId>10f45516-4a04-4025-afc9-fc501341d1eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class,'relative flex')])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel' or . = 'Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>66d20a3d-401a-4ef5-8d77-7aa027cfbbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e6a32424-d4dc-494b-8055-c79fd0b72d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa0749a0-b3a0-472a-b225-e5a4bcfc1c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-211 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>f98a81b6-4811-4e57-b571-f77af175b8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-8</value>
      <webElementGuid>d42945d0-1e2c-4c40-98b7-a4dfaee040de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>4e3e40c7-a920-46e1-a21c-cbd93ea5866a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-8</value>
      <webElementGuid>1bc9d446-1735-47ad-8be6-dc0459f5877f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel</value>
      <webElementGuid>1faa31fe-78df-466a-8da7-c898452044ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-8&quot;)</value>
      <webElementGuid>7250e552-0949-43f5-b3b4-39a1de126adc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-8']</value>
      <webElementGuid>5230aea7-f0a0-4135-9011-882a84b50c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-44']/mat-dialog-container</value>
      <webElementGuid>d0019569-f56e-4fbf-9a4a-a47e2c33d7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>028bf9f9-d9fe-41ce-8e59-cd2c83f7b8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='autotester01@mailinator.com'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>bac24811-a298-49b6-810f-60f1808056dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>64a2af70-b44b-4180-94be-29b341d639db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-8' and (text() = 'Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel' or . = 'Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel')]</value>
      <webElementGuid>31cfbb9f-3730-4ace-9a1c-ec13d2764190</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
