<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_deleteInvitationConfirmationModal</name>
   <tag></tag>
   <elementGuidId>b5faf6d3-1a3a-4fef-85c8-55ee19e9f79c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = concat(&quot; Are you sure you want to delete this contact&quot; , &quot;'&quot; , &quot;s invitation? ConfirmCancel&quot;) or . = concat(&quot; Are you sure you want to delete this contact&quot; , &quot;'&quot; , &quot;s invitation? ConfirmCancel&quot;))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>80bd8c17-ba15-4852-a316-6a1d50afd43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6c276293-8f80-4a35-867c-038f527fa704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72fc3513-651b-41f2-a540-da52c40d4d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-75 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>f3d08959-61bf-43db-8dca-dbb289fe342f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-3</value>
      <webElementGuid>f55a1c9f-1248-429a-964f-4b927fa056c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>826729fa-ae87-4be0-a997-d6c267da85eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-3</value>
      <webElementGuid>f4e47377-f46d-4adc-b18d-567591cc5274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Are you sure you want to delete this contact's invitation? ConfirmCancel</value>
      <webElementGuid>fd7b0ece-355a-4e59-b254-cb94c365cfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-3&quot;)</value>
      <webElementGuid>89162536-f5ce-472f-9936-98576d38f844</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']</value>
      <webElementGuid>cf4ac5de-97c8-449b-86cf-cd00b4a4f0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-10']/mat-dialog-container</value>
      <webElementGuid>fdde131e-64f6-4872-a0e3-43e80f947a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-3', '&quot;', ')')])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>4a856528-8d54-4877-b52c-08320ded7452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::mat-dialog-container[1]</value>
      <webElementGuid>5fef9b9c-f513-4b19-a883-df906865ef09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>63885c66-c99e-45a6-bc90-608136fdcba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-3' and (text() = concat(&quot; Are you sure you want to delete this contact&quot; , &quot;'&quot; , &quot;s invitation? ConfirmCancel&quot;) or . = concat(&quot; Are you sure you want to delete this contact&quot; , &quot;'&quot; , &quot;s invitation? ConfirmCancel&quot;))]</value>
      <webElementGuid>c27c0ba1-9b8c-46cb-809c-258b28d34bce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
