<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete Organization</name>
   <tag></tag>
   <elementGuidId>e9939c5d-d31a-444a-874e-c857d3ab48a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @ng-reflect-permission-type = 'OU_DELETE' and (text() = 'Delete Organization' or . = 'Delete Organization')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@permission-type = 'OU_DELETE' and @ng-reflect-permission-type = 'OU_DELETE' and @ng-reflect-color = 'warn' and (text() = 'Delete Organization' or . = 'Delete Organization')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.ng-tns-c649-67.mat-raised-button.mat-button-base.mat-warn.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>633ffd6e-4582-4e30-a7bf-0eb02e9cebfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ee2af1f-b3b1-43a1-ba31-8926a8755c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>warn</value>
      <webElementGuid>4fc3289d-84e1-4346-9410-dccf7a3d7f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>permission-type</name>
      <type>Main</type>
      <value>OU_DELETE</value>
      <webElementGuid>f18c8d56-cbf1-418f-b776-6980fcb3b3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator ng-tns-c649-67 mat-raised-button mat-button-base mat-warn cdk-focused cdk-mouse-focused</value>
      <webElementGuid>c79aee25-b429-4164-9025-4ca8dba7eeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>warn</value>
      <webElementGuid>991edfc3-9115-40a0-a8f5-f11a907dff2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-permission-type</name>
      <type>Main</type>
      <value>OU_DELETE</value>
      <webElementGuid>7cae6b45-c4f3-4565-b3fe-426fd2772b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Organization</value>
      <webElementGuid>84611171-1a48-48f8-b642-2146f1d6888c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-1-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-82 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;form-settings-submit ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator ng-tns-c649-67 mat-raised-button mat-button-base mat-warn cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>668742c4-cd6d-490b-a071-092d81ad6cc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>0664965c-1ccb-4c12-a1b5-b3944814adb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-1-0']/div/div/button[2]</value>
      <webElementGuid>7964fa5a-d805-4b98-b4e4-166f07e03f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[1]</value>
      <webElementGuid>f74c8f34-6b3d-406c-9b21-0e25555d76cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::button[2]</value>
      <webElementGuid>d5544657-d5e4-4e68-a886-ab56a290f34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Quick Shortcuts'])[1]/preceding::button[5]</value>
      <webElementGuid>5f6a6eaf-2fc1-4173-9f93-ae7bb9de74b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[2]</value>
      <webElementGuid>3bac3878-2111-4446-81f3-8d39515a3d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Delete Organization' or . = 'Delete Organization')]</value>
      <webElementGuid>f4d1dda8-8f3a-486a-b11f-1872b9aadeca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
