<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cloud_files_client</name>
   <tag></tag>
   <elementGuidId>944fc8cc-c15b-4b4d-93cd-0539ba734826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-slide-toggle-5 > label.mat-slide-toggle-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-slide-toggle[@id='mat-slide-toggle-5']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>772cebd0-41cb-4bd4-9751-52a05976f208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-slide-toggle-label</value>
      <webElementGuid>8abde1f1-3afb-4d64-ae62-5b6ca97c86eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>mat-slide-toggle-5-input</value>
      <webElementGuid>ad8c717a-5e3b-4808-a7af-684001f78a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>8a9c5bb5-b51f-4e2f-b81e-480539656fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-slide-toggle-5&quot;)/label[@class=&quot;mat-slide-toggle-label&quot;]</value>
      <webElementGuid>a3553958-90ff-4b67-85f2-b15f721c605c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-slide-toggle[@id='mat-slide-toggle-5']/label</value>
      <webElementGuid>4846980b-127a-40b4-b4f5-d510b7411033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Enable ', '&quot;', 'My Drive', '&quot;', ' for clients')])[1]/following::label[1]</value>
      <webElementGuid>58c899d7-bc3f-47d3-b015-92817e738a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Enable ', '&quot;', 'My Drive', '&quot;', ' for employees')])[1]/following::label[2]</value>
      <webElementGuid>969efd50-ad71-4615-be5e-de2bcfac87c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Enable ', '&quot;', 'My Drive', '&quot;', ' for external users')])[1]/preceding::label[1]</value>
      <webElementGuid>8afe29c3-c259-4538-a57a-cfd46233e66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::label[2]</value>
      <webElementGuid>4f211fad-dcf1-49d9-8d77-52d834874d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/mat-card/mat-card-content/div[2]/mat-slide-toggle/label</value>
      <webElementGuid>46acba04-b7dc-45f5-9c16-79c3389ceb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>2be24347-def5-411d-9eac-d3b597add184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
