<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street</name>
   <tag></tag>
   <elementGuidId>b5722da6-ca77-4a49-a85d-a0976144a844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-8</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@ng-reflect-placeholder = 'Street' and @placeholder = 'Street']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d31305b-80f6-4eb1-a504-d9e8916b3423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>3f6eb20f-e58a-414c-8490-12e7e274acb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c110-45 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ec674b6f-b7da-4c90-a1ac-e5f8cad1f445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>ffa9a6a1-a82a-45bb-836b-4dfa70858ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-placeholder</name>
      <type>Main</type>
      <value>Street</value>
      <webElementGuid>0541d5bf-cb19-42a2-8f26-b3d9addd7bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-8</value>
      <webElementGuid>0b5be63a-fd2c-4ada-aadb-ea2e1387f002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street</value>
      <webElementGuid>d6dea42e-61a9-4471-92ef-17a30602207a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>699e964b-90a6-44ac-829c-7e24796ed12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1fdafe76-a6fb-455f-b37c-8185fa8871c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-8&quot;)</value>
      <webElementGuid>be050800-6bae-4e2e-9331-3407b9017bdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-8']</value>
      <webElementGuid>7a3ba4cd-3493-4068-9c73-f5e649cc7d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/section/div[2]/mat-card/mat-card-content/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>77649db0-f448-4fc3-87fb-957010cc88d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-card/mat-card-content/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>7e976fdd-9912-4988-8578-4b8b8d2e3a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-8' and @placeholder = 'Street']</value>
      <webElementGuid>7f1fa2e4-ce67-4b7e-9354-90ccc252f5b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
