<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-card_Tools</name>
   <tag></tag>
   <elementGuidId>c73f59a4-54da-4d86-921a-fa4739eca3bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-2-1']/div/section[3]/div/mat-card</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-card</value>
      <webElementGuid>ad9c0082-263f-4f96-bbda-e73035cb4488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-card mat-focus-indicator ng-tns-c588-62</value>
      <webElementGuid>8a2f78e2-b321-467f-925e-8af211efcc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tools  Enable or disable tools by clicking on the toggle. ELNet ELSign EL HealthCheck Income and Expense PDF Converter </value>
      <webElementGuid>c6f4c378-fb8f-4f9f-9093-94f7b8c356f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-2-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-78 ng-trigger ng-trigger-translateTab&quot;]/section[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c588-62&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c588-62&quot;]</value>
      <webElementGuid>3583a85a-95dc-40b6-a189-cdf1cca1d202</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-1']/div/section[3]/div/mat-card</value>
      <webElementGuid>aa2894c3-d560-4ea3-8ab0-5f844f86cc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By enabling this option, all join requests via URL will be automatically approved.'])[1]/following::mat-card[1]</value>
      <webElementGuid>8d3a8d70-ffaf-4d83-b69e-4090375cecdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Auto Approve'])[1]/following::mat-card[1]</value>
      <webElementGuid>f81c40b8-9fc9-4a1e-a431-8d7c89341a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/mat-card</value>
      <webElementGuid>5f152b6e-bbdc-4619-bfc6-2eb7cf322ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-card[(text() = ' Tools  Enable or disable tools by clicking on the toggle. ELNet ELSign EL HealthCheck Income and Expense PDF Converter ' or . = ' Tools  Enable or disable tools by clicking on the toggle. ELNet ELSign EL HealthCheck Income and Expense PDF Converter ')]</value>
      <webElementGuid>bc86f1ed-fa0a-46b2-8394-f8086c4ca397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
