<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-card-title_Tools</name>
   <tag></tag>
   <elementGuidId>889009a9-373a-4621-9d33-b14929410572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-card-title[@class = 'mat-card-title' and (text() = ' Tools ' or . = ' Tools ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Tools']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-card-title</value>
      <webElementGuid>fdba6df1-ca60-41d6-92e1-1f42bb4bb684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-card-title</value>
      <webElementGuid>6ab4c209-4f18-471f-be44-6fa6ba9a5837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tools </value>
      <webElementGuid>c7a7a543-c0b2-4b1b-a251-4b259bf4e8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-2-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-78 ng-trigger ng-trigger-translateTab&quot;]/section[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c588-62&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c588-62&quot;]/mat-card-title[@class=&quot;mat-card-title&quot;]</value>
      <webElementGuid>1285a2c2-906f-425f-9d0e-e6859f31cba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-1']/div/section[3]/div/mat-card/mat-card-title</value>
      <webElementGuid>d0bfdf74-d3fc-4b32-9577-14559be9fd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By enabling this option, all join requests via URL will be automatically approved.'])[1]/following::mat-card-title[1]</value>
      <webElementGuid>bf752441-64bc-41cd-b3e3-8d77a5bd7fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Auto Approve'])[1]/following::mat-card-title[1]</value>
      <webElementGuid>ed6c6a3a-683c-4724-96dd-30a3f9c5f428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable or disable tools by clicking on the toggle.'])[1]/preceding::mat-card-title[1]</value>
      <webElementGuid>f2fa6b3c-a2c8-490d-bbd6-4180cb4ed95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELNet'])[2]/preceding::mat-card-title[1]</value>
      <webElementGuid>8fef7a65-3742-4cc5-b80a-7ac1318281ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tools']/parent::*</value>
      <webElementGuid>9a79d4fa-5e0e-4051-93df-4cdfb6e92c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/mat-card/mat-card-title</value>
      <webElementGuid>eca82e86-8b9b-48be-8ff4-564531925c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-card-title[(text() = ' Tools ' or . = ' Tools ')]</value>
      <webElementGuid>b3f5bdaa-a31e-499b-987a-54e83b334d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
