<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_Enable chat message editing</name>
   <tag></tag>
   <elementGuidId>1cb8af5b-725e-44ba-a237-fb68015bc8a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='mat-slide-toggle-thumb-container']//div)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2a843fb3-adae-4403-bab0-7a1f61c38cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665646446173</value>
      <webElementGuid>ffdddd42-2607-4d88-9bf5-fb40fb8a26c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
