<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_EL Sign</name>
   <tag></tag>
   <elementGuidId>95ef23ac-9827-4708-9d25-a90cc5f429b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='mat-slide-toggle-thumb'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0a0786c0-8ce5-4beb-8039-9a1e4ac6e99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665647145977</value>
      <webElementGuid>746ae360-8c3e-4c44-8ae2-502512bcb79b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
