<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_EL Sign</name>
   <tag></tag>
   <elementGuidId>95ef23ac-9827-4708-9d25-a90cc5f429b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[@for='mat-slide-toggle-10-input']//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d4007860-5288-4e4c-bf11-f169f0b17866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665647145977</value>
      <webElementGuid>c703fba6-3876-4c93-9297-9bdd46ff482e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
