<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_EL Sign</name>
   <tag></tag>
   <elementGuidId>95ef23ac-9827-4708-9d25-a90cc5f429b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[@for='mat-slide-toggle-8-input']//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8e11d25d-be5a-4c05-b51d-8509161ce38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665647145977</value>
      <webElementGuid>bc34364c-ebb7-42a4-90d8-eb88d6cffa4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
