<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_EL HealthCheck</name>
   <tag></tag>
   <elementGuidId>bc8dfb75-b4a5-4a5c-9124-8521e74d720d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[@for='mat-slide-toggle-8-input']//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6b0958c1-8c78-49e3-bf27-9902a0f3d424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665647178393</value>
      <webElementGuid>45574302-eeea-4ecf-b867-ba6fc5b9d717</webElementGuid>
   </webElementProperties>
</WebElementEntity>
