<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add</name>
   <tag></tag>
   <elementGuidId>98ecb5ae-ec7e-40ac-a1ba-9483efb1ac00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@ng-reflect-color = 'primary' and (text() = '
            
        Add' or . = '
            
        Add')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and (text() = 'add' or . = 'add')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-mini-fab.mat-button-base.mat-primary.ng-tns-c591-50.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69e81e94-017e-4c5e-ac01-58f4beb99e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>81bf686d-4fb8-44f8-8799-fc5c06c7cfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>d020976f-bfee-4fbf-8f87-d18540cd8d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-mini-fab mat-button-base mat-primary ng-tns-c591-50 ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>5387f539-8563-4b09-b73c-192a18ddcea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>7b3620af-4472-4d36-bcd9-b29918b6e3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>309b047b-bd5d-4e6e-a361-594ca3586ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c481-5 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c481-5 mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;wrapper&quot;]/app-circle-association[@class=&quot;ng-tns-c591-50 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/section[@class=&quot;section-circle-assoc ng-tns-c591-50&quot;]/article[@class=&quot;directory-container ng-tns-c591-50&quot;]/div[@class=&quot;ng-tns-c591-50&quot;]/div[@class=&quot;white-container ng-tns-c591-50&quot;]/div[@class=&quot;button-add-label ng-tns-c591-50&quot;]/button[@class=&quot;mat-focus-indicator mat-mini-fab mat-button-base mat-primary ng-tns-c591-50 ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>85de143b-1221-4011-96d3-7812a48d02f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>8d40115c-38d1-4406-9c42-1af4ba33c686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GG TESTER'])[1]/following::button[1]</value>
      <webElementGuid>2d0248b6-655a-40e7-9494-01eb9b52868e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::button[1]</value>
      <webElementGuid>850fa739-6a2f-47ef-87a9-74e10718a604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>ab9a30d0-7bcb-4410-b435-3279b9c3ada7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'add' or . = 'add')]</value>
      <webElementGuid>af657ec3-b92e-45ad-9330-9cad76d4d3e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
