<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete private circle modal</name>
   <tag></tag>
   <elementGuidId>df6fceef-7af0-40d7-9002-1cce7c478897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Delete Circle Association Are you sure you want to delete association with GG TESTER? DeleteCancel' or . = 'Delete Circle Association Are you sure you want to delete association with GG TESTER? DeleteCancel')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Delete Circle Association Are you sure you want to delete association with GG TESTER? DeleteCancel' or . = 'Delete Circle Association Are you sure you want to delete association with GG TESTER? DeleteCancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>066b7f85-e814-4cf9-9f2a-c39c15db26d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f4bd2d71-f902-472a-b735-5855241f0718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>90999439-4817-4e72-bffe-f4a5a0ad3c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-87 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>2af4f3bc-e802-47a3-b7c6-70b7e8e0e867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-5</value>
      <webElementGuid>862a7c96-1a4e-4d22-b861-4601d767065c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>7e9450e4-0adc-4b04-aa49-e766a346d35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-5</value>
      <webElementGuid>f1edcb12-c860-4f9d-af4a-f364e16cd3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Circle Association Are you sure you want to delete association with GG TESTER? DeleteCancel</value>
      <webElementGuid>5b24405d-bbfd-450f-a742-577f0ad45c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-5&quot;)</value>
      <webElementGuid>8af32f4b-e171-426a-8a8a-185ab76d737b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-5']</value>
      <webElementGuid>4f8e13a4-d0d3-42f7-b4d1-b147874fc5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-27']/mat-dialog-container</value>
      <webElementGuid>0d65c933-b584-4fdb-85f3-10a15dd5f5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Circle Association'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>3207f307-0ad8-4215-897f-bfb0d1544c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Assignment'])[2]/following::mat-dialog-container[1]</value>
      <webElementGuid>c79244df-ab80-4353-aae8-94557dee9877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>16584813-e2ad-4f58-8591-f8fd835cb1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-5' and (text() = 'Delete Circle Association Are you sure you want to delete association with GG TESTER? DeleteCancel' or . = 'Delete Circle Association Are you sure you want to delete association with GG TESTER? DeleteCancel')]</value>
      <webElementGuid>d8662242-d7a9-4854-94f6-a7f74c719ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
