<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Select user</name>
   <tag></tag>
   <elementGuidId>f73e70b1-d84a-4e7d-9b78-3e2d47080ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42f4120d-b57a-48b6-a047-2dff29f1f2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-autocomplete-trigger mat-input-element mat-form-field-autofill-control ng-tns-c110-51 cdk-text-field-autofill-monitored ng-pristine ng-valid ng-touched</value>
      <webElementGuid>7cba4725-523c-4942-bd6c-a9b709f135ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-placeholder</name>
      <type>Main</type>
      <value>Select User</value>
      <webElementGuid>5d152f7b-74ed-47d4-86b2-494e7b258ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-autocomplete</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>eb28e54e-a504-4471-a0d3-54f58c7335d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>0045a8fa-3c67-48ca-af8f-d7c7322fe900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a82e83cf-8d17-4889-a03e-58f3e824448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>acc510a9-7853-4d83-8935-67aa7abeb488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>7ce5a72b-7a07-42dd-9a4d-5a14bd064d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9641253d-9459-4898-9741-2b8743b6a3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c6041d7-561a-44f3-a1ed-ee7f08d123cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-7</value>
      <webElementGuid>6237d494-f3ea-4a04-8cfe-a909340f5895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select User</value>
      <webElementGuid>64b3fa64-dc82-486e-8dfa-e67c27814c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c0ed91e5-54cb-40be-bccd-cd2bcdaa69b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc40d731-853f-4612-9b1d-0883b15174a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>mat-autocomplete-0</value>
      <webElementGuid>25c811d8-0f63-4077-a989-daa897af3b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-7&quot;)</value>
      <webElementGuid>7ee00f7c-89b4-489a-8895-f6bc9d0b0850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-7']</value>
      <webElementGuid>b814a6c7-11f8-4aa1-9d16-b541d318be98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7af91cfc-5823-4e96-9de6-54c52366fe06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-7' and @placeholder = 'Select User']</value>
      <webElementGuid>c93d8fee-82cc-43af-aad2-2a9b84bc7315</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
