<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_Card</name>
   <tag></tag>
   <elementGuidId>575bc39b-cd71-42b2-8359-8066812a816f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-card</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-card.mat-card.mat-focus-indicator.ng-tns-c482-35.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-card</value>
      <webElementGuid>4558a0a3-0ee7-4516-9380-46e9978318d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-card mat-focus-indicator ng-tns-c482-35 ng-star-inserted</value>
      <webElementGuid>c4d850c7-49f8-419e-8a15-62aa4d5536f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email *PasswordSign inForgot password?Don't have an account? Sign up</value>
      <webElementGuid>8dc71b91-513a-42d3-b87e-ce7902069ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login-page[@class=&quot;ng-tns-c482-35 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/section[@class=&quot;ng-tns-c482-35&quot;]/article[@class=&quot;ng-tns-c482-35&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c482-35 ng-star-inserted&quot;]</value>
      <webElementGuid>fc733cab-2f0b-46e5-96a5-9115a4a993b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card</value>
      <webElementGuid>349b2141-1a7f-4988-9992-96f6269875c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
