<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Public_settings</name>
   <tag></tag>
   <elementGuidId>a25e00a4-b4d6-4686-8b06-ee38222a346f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-1']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.settings-form > div.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ff99f2a-4a8b-418b-9b69-44a3851f8225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>6c320bd8-f1ad-44a7-8505-bffb9f0da928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Team Name *Organization UnitTeam TypePublicMember Visibility Allow members to create channels Allow members to do post creation Allow members to comment </value>
      <webElementGuid>ba993318-3fe4-46f0-8a14-4d3476e15a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-50 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;white-container scroll push-top-sm ng-star-inserted&quot;]/div[@class=&quot;settings-form&quot;]/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>b52c2155-f807-4347-aaa4-6b311b102a35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-1']/div/div/div/div</value>
      <webElementGuid>75eed66c-5a70-4a12-a9bb-52127aa8c2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/following::div[8]</value>
      <webElementGuid>92fe32ad-6be3-448d-8f61-2fba4615856c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channels'])[1]/following::div[10]</value>
      <webElementGuid>97a39619-c0cd-40f3-b464-7ce69cd1a306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tab-body[2]/div/div/div/div</value>
      <webElementGuid>19776c17-e854-4359-bc0f-381a0bd27473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Team Name *Organization UnitTeam TypePublicMember Visibility Allow members to create channels Allow members to do post creation Allow members to comment ' or . = 'Team Name *Organization UnitTeam TypePublicMember Visibility Allow members to create channels Allow members to do post creation Allow members to comment ')]</value>
      <webElementGuid>7db1fcb5-9769-4f69-af9c-09d2cc03c146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
