<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Edit CompanyModal</name>
   <tag></tag>
   <elementGuidId>2f0b17ab-627b-4afc-9b39-37a2345e6a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='cdk-overlay-pane']//mat-dialog-container[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-25</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     ' or . = 'Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>c9b774b3-0e6e-40d3-a4c2-d20569e4d74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>18dcd1f2-b3d9-46a5-b4e4-f74903cdd223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fd84418-6b37-498f-aadf-ffafdc4f826d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-266 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>a979da71-fbcd-4852-b8f0-e15727a56bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-25</value>
      <webElementGuid>18f73039-72df-4436-93b0-db8ec2c5ee87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>ec3189eb-f77d-410c-9a1d-84f6ebd86885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     </value>
      <webElementGuid>7917ca6b-ef5b-4397-a868-a55bfc7ce649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-25&quot;)</value>
      <webElementGuid>2771a7c7-b529-4d7b-ad56-0ecdac8a8e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-25']</value>
      <webElementGuid>134c762f-3a72-4545-a079-e47fe1a85820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-74']/mat-dialog-container</value>
      <webElementGuid>8b08428d-4fb9-462d-82e5-b30eb4f49a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOV 2022'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>5d1da81b-05b9-4284-a280-96e3445365d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPDATE'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>827e0076-3f03-4db7-a5b4-ec1cc59cec3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>6cc29c6c-1d46-4ad0-8c5c-cdd83bce7047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-25' and (text() = 'Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     ' or . = 'Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     ')]</value>
      <webElementGuid>8530c6ba-65c0-425c-a399-98667910b505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
