<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_react_heart</name>
   <tag></tag>
   <elementGuidId>737be670-d94a-4cd9-b0d6-4df4903ea28d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@class='mat-button-toggle-button mat-focus-indicator'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @name = 'reaction' and (text() = '💖' or . = '💖')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-button-toggle-37-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d890b14e-9ab7-4aa6-bec7-23e8a6f6c79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31b9ed01-bdd2-4ae7-b547-5fb473e3dc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-toggle-button mat-focus-indicator</value>
      <webElementGuid>cbec1fae-0289-4938-9aef-e722d34eb97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-button-toggle-37-button</value>
      <webElementGuid>437de5e7-6387-46a2-80ec-8b59ca629d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b034b4a-7211-41db-b279-1d57dafb9aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>386ded52-695d-450c-9bc7-5b4f8a3f8b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reaction</value>
      <webElementGuid>ae7a2820-b3e9-4f8a-9b8b-11a65dfd0571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>💖</value>
      <webElementGuid>d1b4d77d-0220-4776-b724-255f4d66fbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-button-toggle-37-button&quot;)</value>
      <webElementGuid>ef93a4da-a87f-4cbd-8bef-589f2abafc29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mat-button-toggle-37-button']</value>
      <webElementGuid>af8c7610-e43a-4a64-837b-86f65a3acb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-button-toggle[@id='mat-button-toggle-37']/button</value>
      <webElementGuid>e55c4469-6d0a-444a-8bf1-c22887cb4a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='👍'])[1]/following::button[1]</value>
      <webElementGuid>479fc27c-a837-4bfd-86e2-a6259aeec03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Chat'])[1]/following::button[2]</value>
      <webElementGuid>9acf2f91-96c3-4511-b8c1-a58622a0046f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='😆'])[1]/preceding::button[1]</value>
      <webElementGuid>62f86ca0-eecb-46be-bde1-fa90597834a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-button-toggle[2]/button</value>
      <webElementGuid>09c02ee8-dc30-45f7-996e-3c45d7ec7ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mat-button-toggle-37-button' and @name = 'reaction' and (text() = '💖' or . = '💖')]</value>
      <webElementGuid>21a51086-4d82-43e2-9f8c-b42eefa682e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
