<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_reply_chat</name>
   <tag></tag>
   <elementGuidId>be094a75-196d-4727-9976-3430a2a466a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Reply test' or . = 'Reply test')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>848d46e7-734a-42bd-bb20-2f752afbc1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665999797817</value>
      <webElementGuid>7cf20d82-780d-4166-86bd-c3b484a0ef02</webElementGuid>
   </webElementProperties>
</WebElementEntity>
