<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Side Menu double arrow icon</name>
   <tag></tag>
   <elementGuidId>42e657b5-5812-4d19-b9e1-b5e6b1809259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/button/span/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.fa.fa-exchange.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>b1ba5fd7-3f4d-4b8e-9c27-938bbd0696a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9915d985-5965-49fa-a35d-a168a4f69da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fontset</name>
      <type>Main</type>
      <value>fontawesome</value>
      <webElementGuid>f3ef4e83-1641-43e9-9907-958a90245851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>fa-exchange</value>
      <webElementGuid>1560688e-8923-4fcc-a05d-e7e2833fab0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate fa fa-exchange mat-icon-no-color</value>
      <webElementGuid>aca2d731-0bc0-433e-8897-ed60066b3ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13cb00ba-4253-4bf2-aa3c-b5e71d8e5758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-font-set</name>
      <type>Main</type>
      <value>fontawesome</value>
      <webElementGuid>3efb4720-45dc-4b9f-aa67-025731d80d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-font-icon</name>
      <type>Main</type>
      <value>fa-exchange</value>
      <webElementGuid>12c012d3-7f19-412b-9c0f-9833c2001d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c463-3 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c463-3 mat-drawer-transition mat-drawer-container-has-open&quot;]/mat-sidenav[@class=&quot;mat-drawer mat-sidenav left-sidenav ng-tns-c174-4 ng-trigger ng-trigger-transform ng-star-inserted mat-drawer-side mat-drawer-opened&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c174-4&quot;]/header[@class=&quot;sidenav-header ng-tns-c174-4&quot;]/ui-current-ou[@class=&quot;ng-tns-c463-3&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;org-name-container&quot;]/button[@class=&quot;mat-focus-indicator mat-menu-trigger org-select mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon notranslate fa fa-exchange mat-icon-no-color&quot;]</value>
      <webElementGuid>1ce6d0e3-ab8c-4c69-aedc-0b49ab23143a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span/mat-icon</value>
      <webElementGuid>e782c56d-9019-4d12-b921-e378bca907c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
