<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete label modal</name>
   <tag></tag>
   <elementGuidId>b225807b-a835-491f-add2-177065435008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel' or . = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>aa04e807-e5f5-46a3-804a-a4d5c8308618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8b4b4bb0-93a5-4316-beb5-dcb64323363b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56cafb60-217a-4ef4-a8cb-d5226a6d4d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-96 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>37cc17f9-2092-4ef9-b5d7-02a11868ae04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-11</value>
      <webElementGuid>9de85ded-8b59-46c9-86cd-1ac883555366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>93b1b662-0ef1-441c-9554-2b877f546e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-11</value>
      <webElementGuid>491c4f14-f029-43c1-8487-61f03d73a75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel</value>
      <webElementGuid>d11f43d0-a79f-4bc6-a681-a0a085d04b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-11&quot;)</value>
      <webElementGuid>ede5cfb2-23a0-40c1-8c8d-d390139f5778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-11']</value>
      <webElementGuid>29101e66-37da-4ad5-a30a-11a8c8d1e3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-27']/mat-dialog-container</value>
      <webElementGuid>d56f58e7-a7c4-401f-aaab-3d7567c1be4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 1'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>78802306-cd57-4616-91a3-bc94117f7b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row per page:'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>56160a50-537d-4613-b13e-b8a91a5e5210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>17d68108-c253-4424-80a7-723d34a6a87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-11' and (text() = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel' or . = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel')]</value>
      <webElementGuid>9aa79c7b-8223-4bd8-becd-f2251ea4005c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
