<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Add New Label</name>
   <tag></tag>
   <elementGuidId>fd3b3eb5-9197-456b-965a-c2b2e123f495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4[(text() = 'Add New Label' or . = 'Add New Label')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[text()='Add New Label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>028812ab-de32-446b-99c5-6c4b2adbb4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>0be109b2-6b05-471a-a629-66ae88d17bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-5</value>
      <webElementGuid>dadfee43-ec38-4142-bfad-93e5907e8202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Label</value>
      <webElementGuid>dcb66a19-6d4f-400b-bea1-8cf5b2e0887d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-5&quot;)</value>
      <webElementGuid>678b03bc-9739-4fc7-9b02-80bdb3674250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-5']</value>
      <webElementGuid>8e25ad6b-94f2-4552-b4dc-ac285ad0c559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-5']/app-dialog-add-label/section/form/h4</value>
      <webElementGuid>0a449b69-f500-4c37-a5a9-13ccf0dae616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 0'])[1]/following::h4[1]</value>
      <webElementGuid>09946bc9-9704-4bc8-b356-57ceb33ebf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row per page:'])[1]/following::h4[1]</value>
      <webElementGuid>52630866-cd9e-41a8-93ab-5dd20ee2a0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label Name'])[1]/preceding::h4[1]</value>
      <webElementGuid>7c597e0e-491a-46fd-bfce-30ddaac0cee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field is required'])[1]/preceding::h4[1]</value>
      <webElementGuid>9b76e565-6b39-4795-a396-3129bace15bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add New Label']/parent::*</value>
      <webElementGuid>1325cda6-9517-47e3-8a5e-a7ac2beedbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/h4</value>
      <webElementGuid>eb1ea4c2-d3d9-4a30-ad45-bce1a29b346e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-5' and (text() = 'Add New Label' or . = 'Add New Label')]</value>
      <webElementGuid>f5bc3dad-193c-40a1-b39c-7259033d3439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
