<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ellipsis_chat setting</name>
   <tag></tag>
   <elementGuidId>3d2962b9-356f-40a6-bf80-6c3c13482bcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-toolbar[@id='chatToolbar']/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>983bec30-71ff-430b-88c3-63533c68b647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0a40455-fa62-4938-b8b7-4f8526d47935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de675f5e-20c4-49f7-8eb6-074edff95ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger mat-icon-button mat-button-base ng-tns-c645-48 ng-star-inserted</value>
      <webElementGuid>8862d003-66d3-4ccd-b95b-622da0f88cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-menu</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f8af22ad-4eeb-4e60-bcc5-2d4dfc4a39c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>e4221b10-a5ce-4597-9f82-1e68697a52ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chatToolbar&quot;)/button[@class=&quot;mat-focus-indicator mat-menu-trigger mat-icon-button mat-button-base ng-tns-c645-48 ng-star-inserted&quot;]</value>
      <webElementGuid>3bf36169-f31b-4358-a684-155970f5869c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[14]</value>
      <webElementGuid>0addde7e-bdf2-4351-8ce2-bb6736a20585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-toolbar[@id='chatToolbar']/button[3]</value>
      <webElementGuid>99cff853-d769-4cc4-a4cd-4d120dc8b5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Chat'])[2]/following::button[3]</value>
      <webElementGuid>dce15d85-bf4a-4677-9a73-b641dcb79b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove group'])[1]/following::button[3]</value>
      <webElementGuid>6f45fc42-0c11-47af-ab96-9aa86a2df1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[2]/preceding::button[1]</value>
      <webElementGuid>b8e29300-f11d-40ee-b2e4-94612382cf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You'])[2]/preceding::button[1]</value>
      <webElementGuid>4e7daefb-8456-464b-b589-9b5ad1bee386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>db93f46e-f9f3-40d5-a826-068c8da2cef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>307df591-f1bb-4b05-9682-22cfd19d563e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
