<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Arrow_btn</name>
   <tag></tag>
   <elementGuidId>e545d2b2-d98f-457f-94e6-ee315520804f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-menu-trigger.org-select.mat-icon-button.mat-button-base.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7537c3c1-2883-47e2-aace-1b391a87f8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8faa546-08fd-42a1-9940-2248d7952c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger org-select mat-icon-button mat-button-base ng-star-inserted</value>
      <webElementGuid>e11eed1c-95b6-44fa-b55e-ac3e59277817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-menu</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>18cc3c21-e6a9-4b3f-ae81-5057d7b9485c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>2cc2a174-8f3e-40b4-bb79-ffce3d408c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;light theme-default os-window fuse-splash-screen-hidden&quot;]/app-root[1]/app-main-page[@class=&quot;ng-tns-c505-0 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/div[@class=&quot;absolute inset-0 flex flex-col min-w-0 overflow-hidden ng-tns-c505-0&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container flex-auto h-full ng-tns-c505-0&quot;]/mat-sidenav[@class=&quot;mat-drawer mat-sidenav light bgc-white ng-tns-c162-1 ng-trigger ng-trigger-transform mat-drawer-side mat-drawer-opened ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c162-1&quot;]/div[@class=&quot;sidenav-container ng-tns-c162-1&quot;]/header[@class=&quot;ng-tns-c505-0&quot;]/ui-current-ou[@class=&quot;ng-tns-c505-0&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;org-name-container&quot;]/button[@class=&quot;mat-focus-indicator mat-menu-trigger org-select mat-icon-button mat-button-base ng-star-inserted&quot;]</value>
      <webElementGuid>946e8781-5a6a-4848-8db0-6616249b6da8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>429dcd0e-dc85-4068-bdc2-cd00fd836121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation Test Org'])[1]/preceding::button[1]</value>
      <webElementGuid>7ceabeb0-09dc-409b-afb0-660ae240cdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AT'])[1]/preceding::button[1]</value>
      <webElementGuid>77d877c6-254b-49eb-a6bb-126e19e651c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>30e540da-ec77-413f-b18b-8b09e78e19bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>a35bf6ca-6f59-42cb-b3d3-601b2893dc96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
