<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_View Share Files Modal</name>
   <tag></tag>
   <elementGuidId>f54ec7a2-7822-4d2f-bac4-d92909d53694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[(text() = 'Share Files closeAdd UsersViewer Notify users Shared withlink Copy Share Link GTGG tester 2 Viewer GTGG tester Viewer  Done ' or . = 'Share Files closeAdd UsersViewer Notify users Shared withlink Copy Share Link GTGG tester 2 Viewer GTGG tester Viewer  Done ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-13</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Share Files closeAdd UsersViewer Notify users Shared withGTGG Tester 3 Viewer GTGG tester 2 Viewer Copy Share Link Save ' or . = 'Share Files closeAdd UsersViewer Notify users Shared withGTGG Tester 3 Viewer GTGG tester 2 Viewer Copy Share Link Save ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>9cac350b-8b41-410f-8684-87f35bd2023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e74994be-a1d8-46b7-a281-f214127e3a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85b36038-adf9-4f70-aea7-c7036e975a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-111 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>f8341c2c-e2ff-48c4-aca7-051ac7d77630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-13</value>
      <webElementGuid>f4ff1b46-c978-4f16-b465-f54f4d221fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>977ffd02-bc96-44d3-a5d8-9e3bfc852aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-13</value>
      <webElementGuid>50e15645-4af4-4eff-8557-414bdadd6a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share Files closeAdd UsersViewer Notify users Shared withGTGG Tester 3 Viewer GTGG tester 2 Viewer Copy Share Link Save </value>
      <webElementGuid>483911bb-cc8a-4b80-8366-f5a37e7e7dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-13&quot;)</value>
      <webElementGuid>1bd00117-318d-4e64-a32b-6ea873ab3ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-13']</value>
      <webElementGuid>4f5a1694-ea3e-4bff-b5bb-5df609fc2510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-33']/mat-dialog-container</value>
      <webElementGuid>679951ba-84c5-4b65-b5e2-e1f9c7226f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JPEG File'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>ed677f4e-363b-4db4-b32b-e1fe270084fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>5b86ac46-039e-41eb-9d0b-19043be03290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>e40c6f88-2039-44cf-a9f6-870d2488cfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-13' and (text() = 'Share Files closeAdd UsersViewer Notify users Shared withGTGG Tester 3 Viewer GTGG tester 2 Viewer Copy Share Link Save ' or . = 'Share Files closeAdd UsersViewer Notify users Shared withGTGG Tester 3 Viewer GTGG tester 2 Viewer Copy Share Link Save ')]</value>
      <webElementGuid>d40b9782-b6c1-4b67-b0ac-dc5e9efdcf8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
