<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_ShareFiles Modal</name>
   <tag></tag>
   <elementGuidId>8f2504f8-fcff-451b-91c7-5231600b58e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[(text() = 'Share Files closeAdd UsersViewer Notify users Shared withlink Copy Share Link Not Shared Done ' or . = 'Share Files closeAdd UsersViewer Notify users Shared withlink Copy Share Link Not Shared Done ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-12</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save ' or . = 'Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>69c7e58c-d7a6-441a-86c5-801db67fc31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5c0e1164-1b66-43fc-b1c6-982b2c49907a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e68c752-e50d-494b-aa2b-f3c09e1ae14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-106 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>65c0050c-70e8-4726-8b71-46cdde951bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-12</value>
      <webElementGuid>ec7cd27f-0dad-4380-a240-4a7ca3ba8ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>ffabdbd5-cec3-4858-8226-b2efd3bc619d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-12</value>
      <webElementGuid>dd99ab4f-3946-4f33-af63-fd4ccb738602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save </value>
      <webElementGuid>cb2ab12b-b1fe-4e9f-9092-9d0e1edc1e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-12&quot;)</value>
      <webElementGuid>aa5fadea-4310-4cbe-a120-51bc51798f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-12']</value>
      <webElementGuid>c08f6fab-4819-41d4-bb38-9b7cbe98813e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-29']/mat-dialog-container</value>
      <webElementGuid>03f7fd26-eb05-4321-b617-3d9d5a00f254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JPEG File'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>6e2ec81a-2d31-494c-b3ee-318e15314961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>948622c7-5b2f-4c94-a485-44f688662033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>ddf0039d-d60b-492a-b3c2-2acb5b67ae6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-12' and (text() = 'Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save ' or . = 'Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save ')]</value>
      <webElementGuid>dc14bd0f-d68f-4e8c-9bff-672e999ce626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
