<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sharefiles_X_button</name>
   <tag></tag>
   <elementGuidId>9a0c5c48-31c9-4ae6-985d-2c13c86eb6a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-dialog-container#mat-dialog-0>app-dialog-share-file-folder>div>mat-icon</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
