<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Now</name>
   <tag></tag>
   <elementGuidId>04043b8a-a643-4240-9012-d51f514b1f44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = ' Now' or . = ' Now')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-radio-label-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'mat-radio-label-content' and (text() = ' Now' or . = ' Now')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>345ca9c6-c247-4413-bf25-e9a3742be113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-label-content</value>
      <webElementGuid>c48c05f5-2e18-40aa-8bf2-7cc937bc2f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Now</value>
      <webElementGuid>5871996c-8bd3-4526-8f20-32b862e59c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-5&quot;)/label[@class=&quot;mat-radio-label&quot;]/div[@class=&quot;mat-radio-label-content&quot;]</value>
      <webElementGuid>57085446-41b1-407c-bc5b-75764af6a0ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-5']/label/div[2]</value>
      <webElementGuid>b19c9911-2db7-4261-aa1e-0018dc0ff195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meeting Title'])[1]/following::div[22]</value>
      <webElementGuid>0ab28593-607a-483e-97e8-5dd219a28d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chat'])[1]/following::div[25]</value>
      <webElementGuid>71b6e4db-c105-4a59-bd67-7988f3ba3b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Contacts'])[1]/preceding::div[7]</value>
      <webElementGuid>e2b585ea-b2b4-428c-92bf-8f64bceb1e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Now']/parent::*</value>
      <webElementGuid>b34a1fa4-4a50-495a-9278-aed08994f82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div[2]</value>
      <webElementGuid>d5ea74b9-3e12-4111-b0ca-c5801031fc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Now' or . = ' Now')]</value>
      <webElementGuid>79aa18ec-e4e8-409a-8597-a46a7d3ad5c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
