<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Schedule</name>
   <tag></tag>
   <elementGuidId>62b161e9-b109-4bbd-afc7-ce4586bb4030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = ' Schedule' or . = ' Schedule')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-6 > label.mat-radio-label > div.mat-radio-label-content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'mat-radio-label-content' and (text() = ' Schedule' or . = ' Schedule')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>32e160e5-7b3f-4bc0-85ee-6feb20771572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-label-content</value>
      <webElementGuid>0792657b-2d3c-4b67-a957-7c440297bf73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Schedule</value>
      <webElementGuid>2a9445fa-69fd-4226-9fd4-ce9c10dbc268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-6&quot;)/label[@class=&quot;mat-radio-label&quot;]/div[@class=&quot;mat-radio-label-content&quot;]</value>
      <webElementGuid>68589e35-c2c0-4698-b5fa-6e73b16055f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-6']/label/div[2]</value>
      <webElementGuid>070e7e57-f1e0-44bb-b60f-df508387911c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meeting Title'])[1]/following::div[28]</value>
      <webElementGuid>b200fee3-f838-43b8-b9bd-4193c961070f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Contacts'])[1]/preceding::div[1]</value>
      <webElementGuid>c092733b-6831-46b6-ade3-d5ca20f08b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select existing contacts'])[1]/preceding::div[4]</value>
      <webElementGuid>aa34e32f-b743-4545-b16c-2cd8be0b308a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Schedule']/parent::*</value>
      <webElementGuid>a914ea23-ea1a-4ac0-a7fa-d2a5eff29148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-radio-button[2]/label/div[2]</value>
      <webElementGuid>68522a24-988f-43cc-9704-4f17027c518e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Schedule' or . = ' Schedule')]</value>
      <webElementGuid>a87123e4-646a-4549-9304-f9b1fb124517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
