<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_Enter a valid phone number (eg 13330001234)</name>
   <tag></tag>
   <elementGuidId>f1c520b7-b371-4adf-b46b-872ea7aa6075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-error-32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[text()='Enter a valid phone number (eg: +13330001234)']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-error[@role = 'alert' and (text() = 'Enter a valid phone number (eg: +13330001234)' or . = 'Enter a valid phone number (eg: +13330001234)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>08a5cc7c-b671-460f-ab86-5e8102d65d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>d069b2f1-625d-40a7-b821-f53e7ec53ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error ng-star-inserted ng-tns-c110-114</value>
      <webElementGuid>741324da-1b82-404f-a357-48b8f87dfe9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-32</value>
      <webElementGuid>b7dcfc69-74c6-4325-8e2d-6d1d023c9c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter a valid phone number (eg: +13330001234)</value>
      <webElementGuid>c072a53f-1bb3-4780-b100-48e32a1cf044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-32&quot;)</value>
      <webElementGuid>fa8288ab-6905-48f6-8b94-4171c8bf96a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-32']</value>
      <webElementGuid>bf04e393-f664-40f3-ac01-74fad19ca0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Guests'])[1]/following::mat-error[1]</value>
      <webElementGuid>688349ae-a5c9-4f7c-b4b6-2323b7fc437a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bringing your old and new contacts together!'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>eac77fe6-136f-4e32-8f28-a3d40fab831e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create meeting'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>657ca9b8-ef20-4d89-99a3-5028d486aa7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter a valid phone number (eg: +13330001234)']/parent::*</value>
      <webElementGuid>888efa4a-e014-4883-9e73-0b196bb76e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>8f7574ff-c291-42e9-85f1-df3f22b24c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-32' and (text() = 'Enter a valid phone number (eg: +13330001234)' or . = 'Enter a valid phone number (eg: +13330001234)')]</value>
      <webElementGuid>ed367bcf-b3b4-454a-a6a2-0bcce5ac38d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
