<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Current Usage-progress-bar-element</name>
   <tag></tag>
   <elementGuidId>33449c97-52b1-4663-81e2-91f2726d2c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-4-0']/div/div[2]/mat-progress-bar/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-progress-bar-buffer.mat-progress-bar-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e189755-e7ea-4974-a3a6-a509aa2de951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-progress-bar-buffer mat-progress-bar-element</value>
      <webElementGuid>0747b7fe-894d-4bd6-9c59-db8bba3720fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-4-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-133 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;progress-bar-container ng-star-inserted&quot;]/mat-progress-bar[@class=&quot;mat-progress-bar mat-primary&quot;]/div[@class=&quot;mat-progress-bar-buffer mat-progress-bar-element&quot;]</value>
      <webElementGuid>aaf07d8e-c6eb-4dde-8828-108dffdbd069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-4-0']/div/div[2]/mat-progress-bar/div</value>
      <webElementGuid>be58c91d-a657-4bf1-bcad-64f194ea9628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-progress-bar/div</value>
      <webElementGuid>1adffc52-ebf8-4a43-8ae8-bb22367023a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
