<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card number___privateStripeFrame35554</name>
   <tag></tag>
   <elementGuidId>ee6d988e-8707-45cc-8d71-cb2dbcc96c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@allow = 'payment *' and @title = 'Secure card number input frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame35554&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b7f19d38-31d3-46be-9c36-4b15f940647b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame35554</value>
      <webElementGuid>9362a081-b53b-4385-a696-f21fa4760753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0fe4b994-e494-4f64-ba4b-a3bcd88a1b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>428ffadd-7979-4d13-b072-ccac0bb0fed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c388c33f-78dd-4f56-833d-e0ffa49f1068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>2f83490e-b493-46a5-9679-ec75564b4881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-903915accbc5f198a5b7dec3f72a2976.html#locale=auto&amp;wait=false&amp;mids[guid]=94d5200c-0d64-400e-9098-0fa941154345d64eee&amp;mids[muid]=2e3da71f-b586-4612-bd2d-d6ccbbd508ab340a78&amp;mids[sid]=0d196711-6bf0-4a9a-8117-4f40e0360e0413d2ae&amp;style[base][::placeholder][color]=grey&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_V3UmIUbv2DgHLS0P9mSHvPza00fx1nrxqK&amp;referrer=https%3A%2F%2Flab.everleagues.com%2Fmain%2Forg%2Fsubscription&amp;controllerId=__privateStripeController3551</value>
      <webElementGuid>501ace09-d9dd-4044-90e2-9009dd760bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
      <webElementGuid>5705a442-39eb-4a31-8efe-a1ad9425fbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>20c94660224a22858f0594f9ab874d04</value>
      <webElementGuid>023af419-827d-4b05-b31c-0a6f356f7c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-card-number&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>c7d1f2b0-c1a2-41b1-abcb-69b6bca13ba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame35554']</value>
      <webElementGuid>c8f3ae9c-8ba1-4d5c-bb05-3af652dd025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-card-number']/div/iframe</value>
      <webElementGuid>d9d188a7-ce28-47d3-9ca7-c02f0595e3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>d3d3a1b5-4f55-4cbe-bc30-f597374d8cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame35554' and @src = 'https://js.stripe.com/v3/elements-inner-card-903915accbc5f198a5b7dec3f72a2976.html#locale=auto&amp;wait=false&amp;mids[guid]=94d5200c-0d64-400e-9098-0fa941154345d64eee&amp;mids[muid]=2e3da71f-b586-4612-bd2d-d6ccbbd508ab340a78&amp;mids[sid]=0d196711-6bf0-4a9a-8117-4f40e0360e0413d2ae&amp;style[base][::placeholder][color]=grey&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_V3UmIUbv2DgHLS0P9mSHvPza00fx1nrxqK&amp;referrer=https%3A%2F%2Flab.everleagues.com%2Fmain%2Forg%2Fsubscription&amp;controllerId=__privateStripeController3551' and @title = 'Secure payment input frame']</value>
      <webElementGuid>d8790830-8bb2-4ac5-8ef3-a8be717c3fa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
