<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog_Add Payment Information Modal</name>
   <tag></tag>
   <elementGuidId>16f3184d-f60d-4d65-9d19-a0b7bbd38a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>b157d9a2-2d3b-415b-84b3-17ee1fa704ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a08ebfa9-437d-4cb2-8be1-044711d55ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>152ce14a-7f6e-4a92-ada2-a379aeec21db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-199 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>fa5048be-255e-439d-9193-40bb52a03a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-5</value>
      <webElementGuid>e151f365-2dc2-45fd-87e3-caf6a5ea89b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>76aa127c-bb08-4dbf-913b-3875edff3873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-5</value>
      <webElementGuid>20282624-691e-4a49-a069-cb86bce35b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Payment InformationNew CardSelect Card *Name on Card *Card numberExpirationCVCZip / Postal Code *Redeem CouponCoupon CodeUpgrade SubscriptionCancel</value>
      <webElementGuid>2dd9e513-87ca-4097-8525-10c1d2fc1d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-5&quot;)</value>
      <webElementGuid>46b81e4a-f250-466e-bf3a-4c4435cd6e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-5']</value>
      <webElementGuid>20d5c7f8-df62-4d86-b1e8-87d65acb0eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-20']/mat-dialog-container</value>
      <webElementGuid>32f072c4-17f7-42fe-aeb0-65f881f9751a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consumed: 0.00 mb'])[2]/following::mat-dialog-container[1]</value>
      <webElementGuid>13aec62d-30b4-4b25-bc37-22ee1455cfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Storage Upload Traffic'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>5de26a68-c5fa-4754-9ae7-ccd65c27d696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>be07c234-5d4c-4fe8-b42f-3b440737b36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-5' and (text() = 'Add Payment InformationNew CardSelect Card *Name on Card *Card numberExpirationCVCZip / Postal Code *Redeem CouponCoupon CodeUpgrade SubscriptionCancel' or . = 'Add Payment InformationNew CardSelect Card *Name on Card *Card numberExpirationCVCZip / Postal Code *Redeem CouponCoupon CodeUpgrade SubscriptionCancel')]</value>
      <webElementGuid>ba561768-a9ba-47a4-bb76-f956338f3db9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
