<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Client column Empty</name>
   <tag></tag>
   <elementGuidId>e77b2b23-3ce1-4848-98c3-8a9088770fc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = ' Clients searchcancel' or . = ' Clients searchcancel')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='white-container'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a43b80c-0db4-469e-baab-5a13f8fc5ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>08782d9f-785f-4653-bd37-9c934e19ba86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>a1c8d65b-7797-4c0b-b68b-59b95a66c2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-container</value>
      <webElementGuid>74d7ca48-26a8-44aa-b1de-45e9794c9d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e3996334-4424-4404-9650-17623e6a104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>838e883d-d665-4fc5-8d82-46bb7fe55e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Clients searchcancel</value>
      <webElementGuid>14d8c530-6835-4b85-9a84-f299308fd664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-2-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-105 ng-trigger ng-trigger-translateTab&quot;]/app-client-assign-by-employee[@class=&quot;tab-container ng-star-inserted&quot;]/div[@class=&quot;white-container&quot;]</value>
      <webElementGuid>a513b889-7d2d-452c-a211-fd234b90e176</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/app-client-assign-by-employee/div[4]</value>
      <webElementGuid>ff3ce2f4-e4c4-4b40-8139-04e4ddac34ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Quick Shortcuts'])[1]/preceding::div[40]</value>
      <webElementGuid>fa415857-2872-4148-ba24-9e0c13c36cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-client-assign-by-employee/div[4]</value>
      <webElementGuid>bee68673-49dc-41f3-b8ac-873df83fae48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Clients searchcancel' or . = ' Clients searchcancel')]</value>
      <webElementGuid>e595b9bf-6938-43cc-aa94-9c574097920c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
