<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GTGG Tester 3</name>
   <tag></tag>
   <elementGuidId>c209d9a4-06e4-46c4-a4a2-72144e47028b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-list-option.mat-list-item.mat-list-option.mat-focus-indicator.mat-list-item-with-avatar.mat-accent.ng-star-inserted > div.mat-list-item-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-1-0']/div/app-client-assign-by-employee/div[4]/div[2]/div[2]/perfect-scrollbar/div/div/mat-selection-list/mat-list-option/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c925aa30-469b-4268-a630-fbf17660ffb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-list-item-content</value>
      <webElementGuid>c59bb7e5-91b3-49b3-abb0-0c617889e738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GTGG Tester 3</value>
      <webElementGuid>443e10e3-b5c7-4ac3-9138-100a633613b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-1-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-80 ng-trigger ng-trigger-translateTab&quot;]/app-client-assign-by-employee[@class=&quot;tab-container ng-star-inserted&quot;]/div[@class=&quot;white-container&quot;]/div[@class=&quot;white-container-body&quot;]/div[@class=&quot;assignment-container&quot;]/perfect-scrollbar[@class=&quot;perfect-scrollbar&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/mat-selection-list[@class=&quot;mat-selection-list mat-list-base unassigned-user&quot;]/mat-list-option[@class=&quot;mat-list-item mat-list-option mat-focus-indicator mat-list-item-with-avatar mat-accent ng-star-inserted&quot;]/div[@class=&quot;mat-list-item-content&quot;]</value>
      <webElementGuid>b0f2fb3a-77a5-4718-8777-e73d64ee2d2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-1-0']/div/app-client-assign-by-employee/div[4]/div[2]/div[2]/perfect-scrollbar/div/div/mat-selection-list/mat-list-option/div</value>
      <webElementGuid>de7a0ac4-f6bd-4d91-8428-88b50f975e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[1]/following::div[19]</value>
      <webElementGuid>ff1bb77f-6d08-427f-8231-465cb0a7dcc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-list-option/div</value>
      <webElementGuid>1081bc5b-d368-4839-99a0-04ae7d464102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'GTGG Tester 3' or . = 'GTGG Tester 3')]</value>
      <webElementGuid>68de41a3-f78c-4161-87bb-fe9742b3ab0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
