<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ACTIVATE</name>
   <tag></tag>
   <elementGuidId>a95caa1d-5d01-4614-95a2-15e8bf838804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.text-upper.mat-raised-button.mat-button-base.mat-accent.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='COVID-19 Information Tracker'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'check_circle ACTIVATE ' or . = 'check_circle ACTIVATE ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38135e28-2291-450a-ae00-79835a04b174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>accent</value>
      <webElementGuid>5d0835ab-d910-495e-ba52-795bbf4c716b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Activate</value>
      <webElementGuid>233aa96b-749f-414b-80f1-a24917517b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-tooltip-trigger mat-raised-button mat-button-base mat-accent</value>
      <webElementGuid>7950cb69-2131-4a1b-b3d9-6f3d9e8f5d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>accent</value>
      <webElementGuid>93c7cd86-4580-4d0c-b790-dc2254dcd824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-message</name>
      <type>Main</type>
      <value>Activate</value>
      <webElementGuid>ea8d803a-3a87-43e7-a5d7-581720c15236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-jqo-1-6</value>
      <webElementGuid>f9fd8c93-294f-482e-8160-4dd352d49991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdk-describedby-host</name>
      <type>Main</type>
      <value>jqo-1</value>
      <webElementGuid>a0828519-6386-4860-9f6b-704a575c5956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>check_circle ACTIVATE </value>
      <webElementGuid>6d24711c-3cf1-4f28-875f-1ea4b7e3471a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c503-0 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c503-0&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;wrapper&quot;]/app-infotracker[@class=&quot;ng-star-inserted&quot;]/table[@class=&quot;trackertable5&quot;]/tr[1]/td[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator mat-tooltip-trigger mat-raised-button mat-button-base mat-accent&quot;]</value>
      <webElementGuid>b080c1ce-c059-41f7-a7c8-46828563ba59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COVID-19 Information Tracker'])[1]/following::button[1]</value>
      <webElementGuid>ad3e17c5-ea1a-4a2d-ae01-10fb924d9af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GG TESTER'])[1]/following::button[1]</value>
      <webElementGuid>9a3da3f3-dfcf-41a8-8b8c-4c3c4cd9d694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACTIVATE'])[1]/preceding::button[1]</value>
      <webElementGuid>e16269c5-ec0b-42e3-aad7-12b1a795bee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>c87aff2c-54c8-4b56-94a1-6fe436586ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'check_circle ACTIVATE ' or . = 'check_circle ACTIVATE ')]</value>
      <webElementGuid>2ea4809e-3b12-483b-b7b8-06155707d86c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
