<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GG Automation</name>
   <tag></tag>
   <elementGuidId>d3b987ba-f7d0-4768-9ada-3074c8287fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tree-node-wrapper/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.node-content-wrapper.node-content-wrapper-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e48495c2-1b64-4a44-ad18-3141f445214c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node-content-wrapper node-content-wrapper-focused</value>
      <webElementGuid>0edac13a-e695-49bb-b443-51b0789c69ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tree-allow-drop</name>
      <type>Main</type>
      <value>(element, $event) => {
      </value>
      <webElementGuid>6ad6af16-c40b-42e7-a3a2-0c30d65f23a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-allow-dragover-styling</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e02e8f67-8798-4f16-8d4a-006c7abe9474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-dragged-element</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>87920050-d1da-4e13-8ecb-fb65fd8529e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a81a8822-19ea-49f5-a37e-629a677da386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GG Automation</value>
      <webElementGuid>b99a0756-fc1d-482e-b8be-8b3b7945518b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-48 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;white-container ng-tns-c649-37&quot;]/div[@class=&quot;user-container-body ng-tns-c649-37&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container ng-tns-c649-37 mat-drawer-transition&quot;]/mat-drawer[@class=&quot;mat-drawer ng-tns-c192-38 ng-trigger ng-trigger-transform mat-drawer-end mat-drawer-side ng-star-inserted mat-drawer-opened&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c192-38&quot;]/perfect-scrollbar[@class=&quot;perfect-scrollbar ng-tns-c192-38&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/div[@class=&quot;table-option-container&quot;]/div[@class=&quot;org-tree-container ng-tns-c649-37&quot;]/ui-org-tree[@class=&quot;ng-tns-c649-37&quot;]/section[@class=&quot;section-org-tree-body&quot;]/div[@class=&quot;tree-wrapper&quot;]/tree-root[1]/tree-viewport[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;angular-tree-component&quot;]/tree-node-collection[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/tree-node[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;tree-node-level-1 tree-node tree-node-leaf ng-star-inserted tree-node-focused&quot;]/tree-node-wrapper[1]/div[@class=&quot;node-wrapper ng-star-inserted&quot;]/div[@class=&quot;node-content-wrapper node-content-wrapper-focused&quot;]</value>
      <webElementGuid>67df8db9-09b1-4b67-8b91-dcd21636de62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div/div[3]/mat-drawer-container/mat-drawer/div/perfect-scrollbar/div/div/div/div[2]/ui-org-tree/section[2]/div[2]/tree-root/tree-viewport/div/div/tree-node-collection/div/tree-node/div/tree-node-wrapper/div/div</value>
      <webElementGuid>fdacdb2c-8679-4bf4-b26c-ce79e5ab6d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search here'])[1]/preceding::div[9]</value>
      <webElementGuid>52b256a6-fff8-4aa1-82ef-0fdb0f55524a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tree-node-wrapper/div/div</value>
      <webElementGuid>ce9a59cd-cb1e-4039-a9c7-b5407450f4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'GG Automation' or . = 'GG Automation')]</value>
      <webElementGuid>6e905093-bb52-4e35-9cca-8afe8049bc6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
