<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Edit User Role</name>
   <tag></tag>
   <elementGuidId>e0bf21e2-28c8-4e0a-a756-70f1fea5ce4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@class = 'mat-dialog-title' and (text() = ' Edit User Role' or . = ' Edit User Role')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h4[@class = 'mat-dialog-title' and (text() = ' Edit User Role' or . = ' Edit User Role')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f79346e1-ed87-416b-8f50-53a728444c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>90a9236d-9ab6-447a-9bee-0c51cf2951c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-1</value>
      <webElementGuid>1da881ea-329c-4d55-b109-836fed7db231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Edit User Role</value>
      <webElementGuid>b836cc44-544f-40b9-a2cc-1841ac443dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-1&quot;)</value>
      <webElementGuid>e7eba7a3-3ada-4a8b-8ac0-cd34741ef8b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-1']</value>
      <webElementGuid>388f1a17-c732-4b93-ae4f-0c72dc9ca48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/app-dialog-edit-user-role/section/form/h4</value>
      <webElementGuid>5402804c-5cb7-4e34-bf6b-65a3019c06c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-title-1', '&quot;', ')')])[1]/following::h4[1]</value>
      <webElementGuid>eca41261-905c-494e-b749-96d3a39d488c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h4[1]</value>
      <webElementGuid>973de25e-4862-4807-8396-c6256513bd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[3]/preceding::h4[1]</value>
      <webElementGuid>b9884a42-3337-4187-a354-7b3d5ef3ae7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[2]/preceding::h4[1]</value>
      <webElementGuid>948349ec-6461-49d1-942b-1ca9432e2e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit User Role']/parent::*</value>
      <webElementGuid>9ecf0063-2645-4c6b-b3d5-f46ee3e60b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/h4</value>
      <webElementGuid>2f6ec3dd-1f73-4311-ac9b-90e2a9d5a441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-1' and (text() = ' Edit User Role' or . = ' Edit User Role')]</value>
      <webElementGuid>3f6100e8-5788-4d6b-9dbf-f751003dbc97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
