<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_cvc___privateStripeFrame35598</name>
   <tag></tag>
   <elementGuidId>c4be74b2-66c6-480d-ac30-f25b8f967957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame35598']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame35598&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fac3a0cc-6e35-4ceb-a6e3-1bf2d0dcafa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame35598</value>
      <webElementGuid>d4cface2-7f59-4978-8388-6e41babbb12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>126477a9-400c-4eec-ad6c-b61a4561786f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4b27c5b-8831-4e62-a6bf-4b338099c68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e7668191-0a16-4800-ab1f-8a125486dad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>d2071d7c-ad25-42be-8240-983aa990c2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-903915accbc5f198a5b7dec3f72a2976.html#locale=auto&amp;wait=false&amp;mids[guid]=94d5200c-0d64-400e-9098-0fa941154345d64eee&amp;mids[muid]=2e3da71f-b586-4612-bd2d-d6ccbbd508ab340a78&amp;mids[sid]=0d196711-6bf0-4a9a-8117-4f40e0360e0413d2ae&amp;style[base][::placeholder][color]=grey&amp;rtl=false&amp;componentName=cardCvc&amp;keyMode=test&amp;apiKey=pk_test_V3UmIUbv2DgHLS0P9mSHvPza00fx1nrxqK&amp;referrer=https%3A%2F%2Flab.everleagues.com%2Fmain%2Forg%2Fsubscription%2Fpayment&amp;controllerId=__privateStripeController3551</value>
      <webElementGuid>477d1bb6-c0c8-456b-aed5-28a660a727e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
      <webElementGuid>d917908a-eb46-46f6-8d04-1c214c2ddfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-card-cvc&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>94a56ff5-85ab-43c1-b235-142160361a58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame35598']</value>
      <webElementGuid>d2eece1c-7a01-445a-9ed3-48942951a485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-card-cvc']/div/iframe</value>
      <webElementGuid>3aaa8cd9-66f0-4622-a964-278cbc1cf6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/iframe</value>
      <webElementGuid>c8e4a927-31a3-4601-b597-1736c590ed5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame35598' and @src = 'https://js.stripe.com/v3/elements-inner-card-903915accbc5f198a5b7dec3f72a2976.html#locale=auto&amp;wait=false&amp;mids[guid]=94d5200c-0d64-400e-9098-0fa941154345d64eee&amp;mids[muid]=2e3da71f-b586-4612-bd2d-d6ccbbd508ab340a78&amp;mids[sid]=0d196711-6bf0-4a9a-8117-4f40e0360e0413d2ae&amp;style[base][::placeholder][color]=grey&amp;rtl=false&amp;componentName=cardCvc&amp;keyMode=test&amp;apiKey=pk_test_V3UmIUbv2DgHLS0P9mSHvPza00fx1nrxqK&amp;referrer=https%3A%2F%2Flab.everleagues.com%2Fmain%2Forg%2Fsubscription%2Fpayment&amp;controllerId=__privateStripeController3551' and @title = 'Secure payment input frame']</value>
      <webElementGuid>721d7dc0-0105-4a2c-8349-45451c5b8725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
