<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Name is required___privateStripeFrame0835</name>
   <tag></tag>
   <elementGuidId>508d9847-82cd-4e85-a06a-36bf9f5a8a39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame0835&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame0835']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame0835</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-fd20b32369be97bdf7c27cb693107a88.html#locale=auto&amp;wait=false&amp;mids[guid]=3900284b-2ce8-4985-a640-bfba7d862f046153f4&amp;mids[muid]=c2c21b7e-dacb-4171-b1d2-7e8e5354237529b615&amp;mids[sid]=eaf99af5-9f1e-4740-9043-78473cb3fd69a2e83d&amp;style[base][::placeholder][color]=grey&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_V3UmIUbv2DgHLS0P9mSHvPza00fx1nrxqK&amp;referrer=https%3A%2F%2Flab.everleagues.com%2Fmain%2Fdashboard&amp;controllerId=__privateStripeController0831</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure card number input frame</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-card-number&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame0835']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-card-number']/div/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame0835' and @src = 'https://js.stripe.com/v3/elements-inner-card-fd20b32369be97bdf7c27cb693107a88.html#locale=auto&amp;wait=false&amp;mids[guid]=3900284b-2ce8-4985-a640-bfba7d862f046153f4&amp;mids[muid]=c2c21b7e-dacb-4171-b1d2-7e8e5354237529b615&amp;mids[sid]=eaf99af5-9f1e-4740-9043-78473cb3fd69a2e83d&amp;style[base][::placeholder][color]=grey&amp;rtl=false&amp;componentName=cardNumber&amp;keyMode=test&amp;apiKey=pk_test_V3UmIUbv2DgHLS0P9mSHvPza00fx1nrxqK&amp;referrer=https%3A%2F%2Flab.everleagues.com%2Fmain%2Fdashboard&amp;controllerId=__privateStripeController0831' and @title = 'Secure card number input frame']</value>
   </webElementXpaths>
</WebElementEntity>
