<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentTitle</name>
   <tag></tag>
   <elementGuidId>7a38470a-f6f3-4910-a130-49efafb14d8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-39</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@class,'mat-input-element mat-form-field-autofill-control')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa9bb021-84bf-462b-880b-3005fb79285b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c110-212 cdk-text-field-autofill-monitored ng-untouched ng-dirty ng-invalid</value>
      <webElementGuid>e6e50cbc-c853-47b7-b039-adfeca7dfa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-39</value>
      <webElementGuid>0e9d0ff0-52dc-4baf-b8dc-30bcd4b2aaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c7802c22-2d47-46af-bb22-fca7e2521a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e9791d8-762a-4f1e-b254-09efce45671b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-39&quot;)</value>
      <webElementGuid>75d03cc8-c97d-4192-b22c-b3c4d840fd3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-39']</value>
      <webElementGuid>fdc4f42f-94a5-4576-bddd-8b7eb7985ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-7-0']/div/app-ezsign-senderdocuments/div/div[2]/table/tr[4]/td/div/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>1ed1e4a8-a808-4249-af41-1e3335bb87ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>59b739ae-dff3-4988-a058-3b365281beae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-39']</value>
      <webElementGuid>83aff845-2a28-4db2-bb92-000367dc9ec4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
