<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_addsigner_testuser005mailinator.com</name>
   <tag></tag>
   <elementGuidId>94367d5c-0abb-446f-8e4f-3c5af9f691b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[text()=' GG TESTER (testuser00005@mailinator.com) '])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2c7c5bc4-ed19-43a8-b90b-c20d513d2e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1690873370829</value>
      <webElementGuid>41b8d83a-8fe1-4663-9b82-2c71f122044f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
