<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Client_Assignment</name>
   <tag></tag>
   <elementGuidId>614273c7-afb3-42c1-a96d-1e0a35033bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@routerlinkactive = 'active' and @href = '/main/operation/client/assign' and (text() = 'keyboard_arrow_rightClient Assignment ' or . = 'keyboard_arrow_rightClient Assignment ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Client Assignment ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mat-focus-indicator.ng-tns-c540-31.mat-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>113fb146-e6cd-4f2f-ab6c-29ea8b488a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>39a4edaa-a814-4fd3-bdb6-97b92a91c4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator ng-tns-c540-31 mat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>8ca32208-8977-49f8-aa48-1d3e1eba0a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>04ee2dce-2cf4-40e6-aea1-83d80f793e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>operation/client/assign</value>
      <webElementGuid>05adb050-76dd-41de-911a-78a0986f4fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active-options</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9fc9fd5c-aede-4f51-b3c2-8445a9e2e9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ba44ca1c-261f-40e6-8e42-8001a317a239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c8843017-f42c-41f4-a239-b066641c38cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/main/operation/client/assign</value>
      <webElementGuid>371f419a-15fb-4b41-90b8-ebd6a2a559b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>keyboard_arrow_rightClient Assignment </value>
      <webElementGuid>a64ffd14-3384-4d5c-89a0-1c277c132a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c481-5 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c481-5 mat-drawer-transition mat-drawer-container-has-open&quot;]/mat-sidenav[@class=&quot;mat-drawer mat-sidenav left-sidenav ng-tns-c195-6 ng-trigger ng-trigger-transform mat-drawer-over ng-star-inserted mat-drawer-opened&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c195-6&quot;]/perfect-scrollbar[@class=&quot;perfect-scrollbar ng-tns-c481-5 ng-star-inserted&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/px-gdn-sidemenu[1]/ul[1]/px-gdn-sideitem[@class=&quot;ng-tns-c540-21 ng-tns-c481-5 ng-star-inserted&quot;]/li[@class=&quot;ng-tns-c540-21 menu-level--1 open&quot;]/ul[@class=&quot;children ng-tns-c540-21 ng-trigger ng-trigger-closeState&quot;]/px-gdn-sideitem[@class=&quot;ng-tns-c540-31 ng-tns-c481-5 ng-star-inserted&quot;]/li[@class=&quot;ng-tns-c540-31 menu-level-0&quot;]/div[@class=&quot;item ng-tns-c540-31&quot;]/a[@class=&quot;mat-focus-indicator ng-tns-c540-31 mat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>5c3b6902-0ecd-487a-8b2f-85cb58ab2225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[2]/following::a[1]</value>
      <webElementGuid>19b89c34-a97c-4570-b966-96a956738936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation'])[1]/following::a[1]</value>
      <webElementGuid>7a88731d-24aa-4760-897d-ddfdebef2561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private Circle'])[1]/preceding::a[1]</value>
      <webElementGuid>287e6236-c05e-4a2a-ace6-041b62e5685a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/main/operation/client/assign')]</value>
      <webElementGuid>c614d1a1-b5c3-42ca-9946-29c4b7fcfbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//px-gdn-sideitem[5]/li/ul/px-gdn-sideitem/li/div/a</value>
      <webElementGuid>0d8b0301-f812-481f-ad4b-546531a30978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/main/operation/client/assign' and (text() = 'keyboard_arrow_rightClient Assignment ' or . = 'keyboard_arrow_rightClient Assignment ')]</value>
      <webElementGuid>687dc880-5238-47e8-8dc1-acf008db8efe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
